#ifndef WRAPPER_ASA066_H_INCLUDED
#define WRAPPER_ASA066_H_INCLUDED

#define r8_normal_01_cdf_inverse(a) R_DBL(FUNCNAME_R8NORMAL01CDFINVERSE(C_SDBL(a)))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8NORMAL01CDFINVERSE(void *);

#endif
