#ifndef WRAPPER_BALL_INTEGRALS_H_INCLUDED
#define WRAPPER_BALL_INTEGRALS_H_INCLUDED

#define i4vec_uniform_ab(a,b,c,d,e) FUNCNAME_I4VECUNIFORMAB(C_DT2I2PI(a,b,c,d,e))
#define r8_gamma(a) R_DBL(FUNCNAME_R8GAMMA(C_SDBL(a)))
#define r8_uniform_01(a) R_DBL(FUNCNAME_R8UNIFORM01(a))
#define r8vec_normal_01(a,b,c) FUNCNAME_R8VECNORMAL01(C_DTPITPI(a,c,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_I4VECUNIFORMAB(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECNORMAL01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8GAMMA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8UNIFORM01(void *);

#endif
