#ifndef WRAPPER_BROWNIAN_MOTION_SIMULATION_H_INCLUDED
#define WRAPPER_BROWNIAN_MOTION_SIMULATION_H_INCLUDED

#define brownian_motion_simulation(a,b,c,d,e,f) FUNCNAME_BROWNIANMOTIONSIMULATION(C_2DT2ITPITPI(a,b,c,d,e,f))

__MATHSUITE __JBURKARDT void * FUNCNAME_BROWNIANMOTIONSIMULATION(void *);

#endif
