#ifndef WRAPPER_BURGERS_SOLUTION_H_INCLUDED
#define WRAPPER_BURGERS_SOLUTION_H_INCLUDED

#define burgers_viscous_time_exact1(a,b,c,d,e,f) FUNCNAME_BURGERSVISCOUSTIMEEXACT1(C_DT2PITITDTPIT(b,e,f,a,d,c))
#define hermite_ek_compute(a,b,c) FUNCNAME_HERMITEEKCOMPUTE(C_DT2PIT(a,b,c))
#define imtqlx(a,b,c,d) R_UCHR(FUNCNAME_IMTQLX(C_DT3PIT(a,b,c,d)))
#define r8vec_even_new(a,b,c) FUNCNAME_R8VECEVENNEW(C_2ITDT(b,c,a))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECEVENNEW(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_BURGERSVISCOUSTIMEEXACT1(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITEEKCOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_IMTQLX(void *);

#endif
