#ifndef WRAPPER_CIRCLE_SEGMENT_H_INCLUDED
#define WRAPPER_CIRCLE_SEGMENT_H_INCLUDED

#define circle_segment_angle_from_chord(a,b,c,d) R_DBL(FUNCNAME_CIRCLESEGMENTANGLEFROMCHORD(C_IT3PIT(a,b,c,d)))
#define circle_segment_angle_from_chord_angles(a,b) R_DBL(FUNCNAME_CIRCLESEGMENTANGLEFROMCHORDANGLES(C_PDBL2(a,b)))
#define circle_segment_angle_from_height(a,b) R_DBL(FUNCNAME_CIRCLESEGMENTANGLEFROMHEIGHT(C_PDBL2(a,b)))
#define circle_segment_area_from_angle(a,b) R_DBL(FUNCNAME_CIRCLESEGMENTAREAFROMANGLE(C_PDBL2(a,b)))
#define circle_segment_area_from_chord(a,b,c,d) R_DBL(FUNCNAME_CIRCLESEGMENTAREAFROMCHORD(C_IT3PIT(a,b,c,d)))
#define circle_segment_area_from_height(a,b) R_DBL(FUNCNAME_CIRCLESEGMENTAREAFROMHEIGHT(C_PDBL2(a,b)))
#define circle_segment_area_from_sample(a,b,c,d,e,f) R_DBL(FUNCNAME_CIRCLESEGMENTAREAFROMSAMPLE(C_IT3PITDTPI(a,b,c,d,e,f)))
#define circle_segment_cdf(a,b,c) R_DBL(FUNCNAME_CIRCLESEGMENTCDF(C_PDBL3(a,b,c)))
#define circle_segment_centroid_from_chord(a,b,c,d) FUNCNAME_CIRCLESEGMENTCENTROIDFROMCHORD(C_IT3PIT(a,b,c,d))
#define circle_segment_centroid_from_height(a,b) FUNCNAME_CIRCLESEGMENTCENTROIDFROMHEIGHT(C_PDBL2(a,b))
#define circle_segment_centroid_from_sample(a,b,c,d,e,f) R_DBL(FUNCNAME_CIRCLESEGMENTCENTROIDFROMSAMPLE(C_IT3PITDTPI(a,b,c,d,e,f)))
#define circle_segment_contains_point(a,b,c,d,e) R_UCHR(FUNCNAME_CIRCLESEGMENTCONTAINSPOINT(C_ITPIT2ITPIT(a,b,c,d,e)))
#define circle_segment_height_from_angle(a,b) R_DBL(FUNCNAME_CIRCLESEGMENTHEIGHTFROMANGLE(C_PDBL2(a,b)))
#define circle_segment_height_from_area(a,b) R_DBL(FUNCNAME_CIRCLESEGMENTHEIGHTFROMAREA(C_PDBL2(a,b)))
#define circle_segment_height_from_chord(a,b,c,d) R_DBL(FUNCNAME_CIRCLESEGMENTHEIGHTFROMCHORD(C_IT3PIT(a,b,c,d)))
#define circle_segment_rotation_from_chord(a,b,c,d) R_DBL(FUNCNAME_CIRCLESEGMENTROTATIONFROMCHORD(C_IT3PIT(a,b,c,d)))
#define circle_segment_sample_from_chord(a,b,c,d,e,f,g,h) FUNCNAME_CIRCLESEGMENTROTATIONFROMCHORD(C_IT3PITDTPI2PIT(a,b,c,d,e,f,g,h))
#define circle_segment_sample_from_height(a,b,c,d,e,f) FUNCNAME_CIRCLESEGMENTSAMPLEFROMHEIGHT(C_2ITDTPI2PIT(a,b,c,d,e,f))
#define circle_segment_width_from_height(a,b) FUNCNAME_CIRCLESEGMENTWIDTHFROMHEIGHT(C_PDBL2(a,b))


__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTANGLEFROMCHORD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTAREAFROMCHORD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTCONTAINSPOINT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTHEIGHTFROMCHORD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTSAMPLEFROMCHORD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTSAMPLEFROMHEIGHT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTCENTROIDFROMCHORD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTCENTROIDFROMHEIGHT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTCENTROIDFROMSAMPLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTANGLEFROMCHORDANGLES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTANGLEFROMHEIGHT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTAREAFROMSAMPLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTAREAFROMANGLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTAREAFROMHEIGHT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTHEIGHTFROMANGLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTHEIGHTFROMAREA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTWIDTHFROMHEIGHT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTROTATIONFROMCHORD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLESEGMENTCDF(void *);

#endif
