#ifndef WRAPPER_CIRCLE_ARC_GRID_H_INCLUDED
#define WRAPPER_CIRCLE_ARC_GRID_H_INCLUDED

#define circle_arc_grid(a,b,c,d,e) FUNCNAME_CIRCLEARCGRID(C_DTIT3PIT(d,a,b,c,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_CIRCLEARCGRID(void *);

#endif
