#ifndef WRAPPER_CLENSHAW_CURTIS_RULE_H_INCLUDED
#define WRAPPER_CLENSHAW_CURTIS_RULE_H_INCLUDED

#define clenshaw_curtis_compute(a,b,c) FUNCNAME_CLENSHAWCURTISCOMPUTE(C_DT2PIT(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_CLENSHAWCURTISCOMPUTE(void *);

#endif
