#ifndef WRAPPER_COMBINATION_LOCK_H_INCLUDED
#define WRAPPER_COMBINATION_LOCK_H_INCLUDED

#define bicycle_lock(a) R_USHRT(FUNCNAME_BICYCLELOCK(C_SUSHRT(a)))
#define combination_lock(a,b,c) R_USHRT(FUNCNAME_COMBINATIONLOCK(C_2DTPI(a,b,c)))
#define combination_next(a,b,c,d) FUNCNAME_COMBINATIONNEXT(C_2DTPIPB(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_COMBINATIONLOCK(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_COMBINATIONNEXT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_BICYCLELOCK(void *);

#endif
