#ifndef WRAPPER_COSINE_TRANSFORM_H_INCLUDED
#define WRAPPER_COSINE_TRANSFORM_H_INCLUDED

#define cosine_transform_data(a,b) FUNCNAME_COSINETRANSFORMDATA(C_DTPIT(a,b))
#define cosine_transform_inverse(a,b) FUNCNAME_COSINETRANSFORMINVERSE(C_DTPIT(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_COSINETRANSFORMDATA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_COSINETRANSFORMINVERSE(void *);

#endif
