#ifndef WRAPPER_CUBE_EXACTNESS_H_INCLUDED
#define WRAPPER_CUBE_EXACTNESS_H_INCLUDED

#define legendre_3d_monomial_integral(a,b,c) R_DBL(FUNCNAME_LEGENDRE3DMONOMIALINTEGRAL(C_PDT2PIT(c,a,b)))

__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDRE3DMONOMIALINTEGRAL(void *);

#endif
