#ifndef WRAPPER_CUBE_ARBQ_RULE_H_INCLUDED
#define WRAPPER_CUBE_ARBQ_RULE_H_INCLUDED

#define cube_arbq(a,b,c,d) FUNCNAME_CUBEARBQ(C_2DT2PIT(a,b,c,d))
#define cube_arbq_size(a) R_USHRT(FUNCNAME_CUBEARBQSIZE(C_SUSHRT(a)))
#define cube_rule01(a,b,c) FUNCNAME_CUBERULE01(C_DT2PIT(a,b,c))
#define cube_rule02(a,b,c) FUNCNAME_CUBERULE02(C_DT2PIT(a,b,c))
#define cube_rule03(a,b,c) FUNCNAME_CUBERULE03(C_DT2PIT(a,b,c))
#define cube_rule04(a,b,c) FUNCNAME_CUBERULE04(C_DT2PIT(a,b,c))
#define cube_rule05(a,b,c) FUNCNAME_CUBERULE05(C_DT2PIT(a,b,c))
#define cube_rule06(a,b,c) FUNCNAME_CUBERULE06(C_DT2PIT(a,b,c))
#define cube_rule07(a,b,c) FUNCNAME_CUBERULE07(C_DT2PIT(a,b,c))
#define cube_rule08(a,b,c) FUNCNAME_CUBERULE08(C_DT2PIT(a,b,c))
#define cube_rule09(a,b,c) FUNCNAME_CUBERULE09(C_DT2PIT(a,b,c))
#define cube_rule10(a,b,c) FUNCNAME_CUBERULE10(C_DT2PIT(a,b,c))
#define cube_rule11(a,b,c) FUNCNAME_CUBERULE11(C_DT2PIT(a,b,c))
#define cube_rule12(a,b,c) FUNCNAME_CUBERULE12(C_DT2PIT(a,b,c))
#define cube_rule13(a,b,c) FUNCNAME_CUBERULE13(C_DT2PIT(a,b,c))
#define cube_rule14(a,b,c) FUNCNAME_CUBERULE14(C_DT2PIT(a,b,c))
#define cube_rule15(a,b,c) FUNCNAME_CUBERULE15(C_DT2PIT(a,b,c))


__MATHSUITE __JBURKARDT void * FUNCNAME_CUBEARBQ(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE02(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE04(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE05(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE08(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE09(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE10(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE11(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE12(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE13(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE14(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBERULE15(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CUBEARBQSIZE(void *);

#endif
