#ifndef WRAPPER_DUEL_SIMULATION_H_INCLUDED
#define WRAPPER_DUEL_SIMULATION_H_INCLUDED

#define duel_result(a,b) R_USHRT(FUNCNAME_DUELRESULT(C_PDBL2(a,b)))
#define random_double() R_DBL(FUNCNAME_RANDOMDOUBLE(NULL))

__MATHSUITE __JBURKARDT void * FUNCNAME_RANDOMDOUBLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DUELRESULT(void *);

#endif
