#ifndef WRAPPER_ELLIPSE_GRID_H_INCLUDED
#define WRAPPER_ELLIPSE_GRID_H_INCLUDED

#define ellipse_grid(a,b,c,d) FUNCNAME_ELLIPSEGRID(C_2DT2PIT(a,d,b,c))
#define ellipse_grid_count(a,b,c) R_DBL(FUNCNAME_ELLIPSEGRIDCOUNT(C_DT2PIT(a,b,c)))
#define i4_ceiling(a) R_INT(FUNCNAME_I4CEILING(C_SDBL(a)))

__MATHSUITE __JBURKARDT void * FUNCNAME_ELLIPSEGRIDCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_ELLIPSEGRID(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_I4CEILING(void *);

#endif

