#ifndef WRAPPER_ELLIPSOID_MONTE_CARLO_H_INCLUDED
#define WRAPPER_ELLIPSOID_MONTE_CARLO_H_INCLUDED

#define ellipsoid_sample(a,b,c,d,e,f) FUNCNAME_ELLIPSOIDSAMPLE(C_2DT2PITITPI(a,b,c,d,e,f))
#define ellipsoid_volume(a,b,c,d) R_DBL(FUNCNAME_ELLIPSOIDVOLUME(C_DTIT2PIT(a,d,b,c)))
#define hypersphere_unit_volume(a) R_DBL(FUNCNAME_HYPERSPHEREUNITVOLUME(C_SUSHRT(a)))
#define r8po_factor(a,b) FUNCNAME_R8POFACTOR(C_DTPIT(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_ELLIPSOIDVOLUME(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_ELLIPSOIDSAMPLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8POFACTOR(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHEREUNITVOLUME(void *);

#endif
