#ifndef WRAPPER_ELLIPSE_MONTE_CARLO_H_INCLUDED
#define WRAPPER_ELLIPSE_MONTE_CARLO_H_INCLUDED

#define ellipse_area1(a,b) R_DBL(FUNCNAME_ELLIPSEAREA1(C_ITPIT(b,a)))
#define ellipse_area2(a,b,c,d) R_DBL(FUNCNAME_ELLIPSEAREA2(C_PDBL4(a,b,c,d)))
#define ellipse_sample(a,b,c,d) FUNCNAME_ELLIPSESAMPLE(C_DTPITITPI(a,b,c,d))
#define r8po_fa(a,b,c) R_USHRT(FUNCNAME_R8POFA(C_2DTPIT(a,b,c)))
#define r8po_sl(a,b,c,d) FUNCNAME_R8POSL(C_2DT2PIT(a,b,c,d))
#define uniform_in_sphere01_map(a,b,c) FUNCNAME_UNIFORMINSPHERE01MAP(C_2DTPI(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_ELLIPSEAREA1(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_ELLIPSEAREA2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8POFA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8POSL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_ELLIPSESAMPLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_UNIFORMINSPHERE01MAP(void *);

#endif
