#ifndef WRAPPER_EXACTNESS_H_INCLUDED
#define WRAPPER_EXACTNESS_H_INCLUDED

#define hermite_exactness(a,b,c,d) FUNCNAME_HERMITEEXACTNESS(C_2DT2PIT(a,d,b,c))
#define hermite_integral(a) R_DBL(FUNCNAME_HERMITEINTEGRAL(C_SUSHRT(a)))
#define laguerre_exactness(a,b,c,d) FUNCNAME_LAGUERREEXACTNESS(C_2DT2PIT(a,d,b,c))
#define laguerre_integral(a) R_DBL(FUNCNAME_LAGUERREINTEGRAL(C_SUSHRT(a)))
#define legendre_exactness(a,b,c,d) FUNCNAME_LEGENDREEXACTNESS(C_2DT2PIT(a,d,b,c))
#define legendre_integral(a) R_DBL(FUNCNAME_LEGENDREINTEGRAL(C_SUSHRT(a)))
#define legendre_monomial_quadrature(a) R_DBL(FUNCNAME_LEGENDREMONOMIALQUADRATURE(C_2DT2PIT(a)))

__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITEEXACTNESS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGUERREEXACTNESS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDREEXACTNESS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDREMONOMIALQUADRATURE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITEINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGUERREINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDREINTEGRAL(void *);

#endif

