#ifndef WRAPPER_FEM1D_HEAT_STEADY_H_INCLUDED
#define WRAPPER_FEM1D_HEAT_STEADY_H_INCLUDED

#define fem1d_heat_steady(a,b,c,d,e,f,g,h) FUNCNAME_FEM1DHEATSTEADY(C_DT4IT2FITPIT(a,b,c,d,e,f,g,h))
#define r8mat_zero_new(a,b) FUNCNAME_R8MATZERONEW(C_PUSHRT2(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATZERONEW(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEM1DHEATSTEADY(void *);

#endif

