#ifndef WRAPPER_FEM1D_LAGRANGE_H_INCLUDED
#define WRAPPER_FEM1D_LAGRANGE_H_INCLUDED

#define fem1d_lagrange_stiffness(a,b,c,d,e,f,g) FUNCNAME_FEM1DLAGRANGESTIFFNESS(C_DTPITDTFIT3PIT(a,b,c,d,e,f,g))
#define lagrange_derivative(a,b,c,d) FUNCNAME_LAGRANGEDERIVATIVE(C_2DT2PIT(a,c,b,d))
#define legendre_set(a,b,c) FUNCNAME_LEGENDRESET(C_DT2PIT(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDRESET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEDERIVATIVE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEM1DLAGRANGESTIFFNESS(void *);

#endif
