#ifndef WRAPPER_FEM1D_PROJECT_H_INCLUDED
#define WRAPPER_FEM1D_PROJECT_H_INCLUDED

#define piecewise_linear_product_quad(a,b,c,d,e,f,g,h,i) R_DBL(FUNCNAME_PIECEWISELINEARPRODUCTQUAD(C_2ITDT2PITDT2PITDT(a,b,c,d,e,f,g,h,i)))
#define r8vec_bracket3(a,b,c,d) FUNCNAME_R8VECBRACKET3(C_DTPITITPI(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_PIECEWISELINEARPRODUCTQUAD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECBRACKET3(void *);

#endif
