#ifndef WRAPPER_FEM1D_BVP_QUADRATIC_H_INCLUDED
#define WRAPPER_FEM1D_BVP_QUADRATIC_H_INCLUDED

#define fem1d_bvp_quadratic(a,b,c,d,e) FUNCNAME_FEM1DBVPQUADRATIC(C_DT3FITPIT(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_FEM1DBVPQUADRATIC(void *);

#endif
