#ifndef WRAPPER_HIGH_CARD_SIMULATION_H_INCLUDED
#define WRAPPER_HIGH_CARD_SIMULATION_H_INCLUDED

#define high_card_probability(a) FUNCNAME_HIGHCARDPROBABILITY(a)
#define high_card_shuffle(a,b) FUNCNAME_HIGHCARDSHUFFLE(C_DTPI(a,b))
#define high_card_simulation(a,b,c,d) R_DBL(FUNCNAME_HIGHCARDSIMULATION(C_3DTPI(a,b,c,d)))
#define perm_uniform_new(a,b) FUNCNAME_PERMUNIFORMNEW(C_DTPI(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_HIGHCARDSIMULATION(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HIGHCARDPROBABILITY(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HIGHCARDSHUFFLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PERMUNIFORMNEW(void *);

#endif
