#ifndef WRAPPER_HYPERCUBE_GRID_H_INCLUDED
#define WRAPPER_HYPERCUBE_GRID_H_INCLUDED

#define hypercube_grid(a,b,c,d,e,f) FUNCNAME_HYPERCUBEGRID(C_2DTPDT2PITPDT(a,b,c,d,e,f))

__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERCUBEGRID(void *);

#endif
