#ifndef WRAPPER_HYPERSPHERE_INTEGRALS_H_INCLUDED
#define WRAPPER_HYPERSPHERE_INTEGRALS_H_INCLUDED

#define hypersphere01_area(a) R_DBL(FUNCNAME_HYPERSPHERE01AREA(C_SUSHRT(a)))
#define hypersphere01_monomial_integral(a,b) R_DBL(FUNCNAME_HYPERSPHERE01MONOMIALINTEGRAL(C_DTPI(a,b)))
#define hypersphere01_sample(a,b,c) FUNCNAME_HYPERSPHERE01SAMPLE(C_2DTPI(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERE01MONOMIALINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERE01SAMPLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERE01AREA(void *);

#endif
