#ifndef WRAPPER_HYPERSPHERE_PROPERTIES_H_INCLUDED
#define WRAPPER_HYPERSPHERE_PROPERTIES_H_INCLUDED

#define cartesian_to_hypersphere(a,b,c,d,e,f) FUNCNAME_CARTESIANTOHYPERSPHERE(C_2DT4PIT(a,b,c,d,e,f))
#define hypersphere_01_interior_uniform(a,b,c) FUNCNAME_HYPERSPHERE01INTERIORUNIFORM(C_2DTPI(a,b,c))
#define hypersphere_01_surface_uniform(a,b,c) FUNCNAME_HYPERSPHERE01SURFACEUNIFORM(C_2DTPI(a,b,c))
#define hypersphere_01_volume(a) R_DBL(FUNCNAME_HYPERSPHERE01VOLUME(C_SUSHRT(a)))
#define hypersphere_01_area(a) R_DBL(FUNCNAME_HYPERSPHERE001AREA(C_SUSHRT(a)))
#define hypersphere_area(a,b) R_DBL(FUNCNAME_HYPERSPHEREAREA(C_DTIT(a,b)))
#define hypersphere_stereograph(a,b,c) FUNCNAME_HYPERSPHERESTEREOGRAPH(C_2DTPIT(a,b,c))
#define hypersphere_stereograph_inverse(a,b,c) FUNCNAME_HYPERSPHERESTEREOGRAPHINVERSE(C_2DTPIT(a,b,c))
#define hypersphere_surface_uniform(a,b,c,d,e) FUNCNAME_HYPERSPHERESURFACEUNIFORM(C_2DTITPITPI(a,b,c,d,e))
#define hypersphere_to_cartesian(a,b,c,d,e) FUNCNAME_HYPERSPHERETOCARTESIAN(C_2DT3PIT(a,b,c,d,e))
#define hypersphere_volume(a,b) R_DBL(FUNCNAME_HYPERSPHEREVOLUME(C_DTIT(a,b)))
#define sphere_stereograph(a,b,c) FUNCNAME_SPHERESTEREOGRAPH(C_2DTPIT(a,b,c))
#define sphere_stereograph_inverse(a,b,c) FUNCNAME_SPHERESTEREOGRAPHINVERSE(C_2DTPIT(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_CARTESIANTOHYPERSPHERE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERE01INTERIORUNIFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERE01SURFACEUNIFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERESTEREOGRAPH(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERESTEREOGRAPHINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERESURFACEUNIFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERETOCARTESIAN(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHEREVOLUME(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERESTEREOGRAPH(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERESTEREOGRAPHINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERE01VOLUME(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHERE001AREA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HYPERSPHEREAREA(void *);

#endif
