#ifndef WRAPPER_IMAGE_COMPONENTS_H_INCLUDED
#define WRAPPER_IMAGE_COMPONENTS_H_INCLUDED

#define i4block_components(a,b,c,d,e) R_INT(FUNCNAME_I4BLOCKCOMPONENTS(C_3DT2PI(a,b,c,d,e)))
#define i4mat_components(a,b,c,d) R_INT(FUNCNAME_I4MATCOMPONENTS(C_2DT2PI(a,b,c,d)))
#define i4vec_components(a,b,c) R_INT(FUNCNAME_I4VECCOMPONENTS(C_DT2PI(a,b,c)))

__MATHSUITE __JBURKARDT void * FUNCNAME_I4BLOCKCOMPONENTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_I4MATCOMPONENTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_I4VECCOMPONENTS(void *);

#endif
