#ifndef WRAPPER_IMAGE_DENOISE_H_INCLUDED
#define WRAPPER_IMAGE_DENOISE_H_INCLUDED

#define gray_median_news(a,b,c) FUNCNAME_GRAYMEDIANNEWS(C_2DTPI(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_GRAYMEDIANNEWS(void *);

#endif

