#ifndef WRAPPER_INTERP_H_INCLUDED
#define WRAPPER_INTERP_H_INCLUDED

#define cc_abscissas(a) FUNCNAME_CCABSCISSAS(C_SUSHRT(a))
#define cc_abscissas_ab(a,b,c) FUNCNAME_CCABSCISSASAB(C_2ITDT(a,b,c))
#define f1_abscissas(a) FUNCNAME_F1ABSCISSAS(C_SUSHRT(a))
#define f1_abscissas_ab(a,b,c) FUNCNAME_F1ABSCISSASAB(C_2ITDT(a,b,c))
#define f2_abscissas(a) FUNCNAME_F2ABSCISSAS(C_SUSHRT(a))
#define f2_abscissas_ab(a,b,c) FUNCNAME_F2ABSCISSASAB(C_2ITDT(a,b,c))
#define interp_lagrange(a,b,c,d,e,f) FUNCNAME_INTERPLAGRANGE(C_3DT3PIT(a,b,e,c,d,f))
#define interp_linear(a,b,c,d,e,f) FUNCNAME_INTERPLINEAR(C_3DT3PIT(a,b,e,c,d,f))
#define interp_nearest(a,b,c,d,e,f) FUNCNAME_INTERPNEAREST(C_3DT3PIT(a,b,e,c,d,f))
#define lagrange_value(a,b,c,d) FUNCNAME_LAGRANGEVALUE(C_2DT2PIT(a,c,b,d))
#define ncc_abscissas(a) FUNCNAME_NCCABSCISSAS(C_SUSHRT(a))
#define ncc_abscissas_ab(a,b,c) FUNCNAME_NCCABSCISSASAB(C_2ITDT(a,b,c))
#define nco_abscissas(a) FUNCNAME_NCOABSCISSAS(C_SUSHRT(a))
#define nco_abscissas_ab(a,b,c) FUNCNAME_NCOABSCISSASAB(C_2ITDT(a,b,c))
#define parameterize_arc_length(a,b,c) FUNCNAME_PARAMETERIZEARCLENGTH(C_2DTPIT(a,b,c))
#define parameterize_index(a,b,c) FUNCNAME_PARAMETERIZEINDEX(C_2DTPIT(a,b,c))
#define r8mat_expand_linear2(a,b,c,d,e) FUNCNAME_R8MATEXPANDLINEAR2(C_2DTPIT2DT(a,b,c,d,e))
#define r8vec_ascends_strictly(a,b) R_UCHR(FUNCNAME_R8VECASCENDSSTRICTLY(C_DTPIT(a,b)))
#define r8vec_bracket0(a,b,c,d,e) FUNCNAME_R8VECBRACKET0(C_DTPITIT2PI(a,b,c,d,e))
#define r8vec_expand_linear2(a,b,c,d,e) FUNCNAME_R8VECEXPANDLINEAR2(C_2DTPIT2DT(a,c,b,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECASCENDSSTRICTLY(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECBRACKET0(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CCABSCISSAS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CCABSCISSASAB(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_F1ABSCISSAS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_F1ABSCISSASAB(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_F2ABSCISSAS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_F2ABSCISSASAB(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_INTERPLAGRANGE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_INTERPLINEAR(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_INTERPNEAREST(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEVALUE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NCCABSCISSAS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NCCABSCISSASAB(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NCOABSCISSAS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NCOABSCISSASAB(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PARAMETERIZEARCLENGTH(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PARAMETERIZEINDEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATEXPANDLINEAR2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECEXPANDLINEAR2(void *);

#endif
