#ifndef WRAPPER_ISING_2D_SIMULATION_H_INCLUDED
#define WRAPPER_ISING_2D_SIMULATION_H_INCLUDED

#define ising_2d_agree(a,b,c,d) FUNCNAME_ISING2DAGREE(C_2DT2PI(a,b,c,d))
#define ising_2d_initialize(a,b,c,d) FUNCNAME_ISING2DINITIALIZE(C_2DTITPI(a,b,c,d))
#define r8mat_uniform_01(a,b,c,d) FUNCNAME_R8MATUNIFORM01(C_2DTPIPIT(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_ISING2DAGREE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATUNIFORM01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_ISING2DINITIALIZE(void *);

#endif
