#ifndef WRAPPER_JACOBI_EIGENVALUE_H_INCLUDED
#define WRAPPER_JACOBI_EIGENVALUE_H_INCLUDED

#define jacobi_eigenvalue(a,b,c,d,e,f,g) FUNCNAME_JACOBIEIGENVALUE(C_DTPITI2PIT2PI(a,b,c,d,e,f,g))
#define r8mat_diag_get_vector(a,b,c) FUNCNAME_R8MATDIAGGETVECTOR(C_DT2PIT(a,b,c))
#define r8mat_identity(a,b) FUNCNAME_R8MATIDENTITY(C_DTPIT(a,b))
#define r8mat_is_eigen_right(a,b,c,d,e) R_DBL(FUNCNAME_R8MATISEIGENRIGHT(C_2DT3PIT(a,b,c,d,e)))

__MATHSUITE __JBURKARDT void * FUNCNAME_JACOBIEIGENVALUE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATDIAGGETVECTOR(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATIDENTITY(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATISEIGENRIGHT(void *);

#endif
