#ifndef WRAPPER_KNAPSACK_01_H_INCLUDED
#define WRAPPER_KNAPSACK_01_H_INCLUDED

#define subset_gray_next(a,b,c,d,e) R_UCHR(FUNCNAME_SUBSETGRAYNEXT(C_DT4PI(a,b,c,d,e)))

__MATHSUITE __JBURKARDT void * FUNCNAME_SUBSETGRAYNEXT(void *);

#endif
