#ifndef WRAPPER_LAGRANGE_INTERP_1D_H_INCLUDED
#define WRAPPER_LAGRANGE_INTERP_1D_H_INCLUDED

#define lagrange_value_1d(a,b,c,d,e) FUNCNAME_LAGRANGEVALUE1D(C_2DT3PIT(a,d,b,c,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEVALUE1D(void *);

#endif
