#ifndef WRAPPER_LAGRANGE_INTERP_ND_H_INCLUDED
#define WRAPPER_LAGRANGE_INTERP_ND_H_INCLUDED

#define cc_compute_points(a) FUNCNAME_CCCOMPUTEPOINTS(C_SUSHRT(a))
#define lagrange_interp_nd_grid(a,b,c,d,e) FUNCNAME_LAGRANGEINTERPNDGRID(C_PIT2DTPDTPIT(c,a,e,b,d))
#define lagrange_interp_nd_grid2(a,b,c,d,e) FUNCNAME_LAGRANGEINTERPNDGRID2(C_PIT2DTPDTPIT(c,a,e,b,d))
#define lagrange_interp_nd_size(a,b) R_USHRT(FUNCNAME_LAGRANGEINTERPNDSIZE(C_DTPI(a,b)))
#define lagrange_interp_nd_size2(a,b) R_USHRT(FUNCNAME_LAGRANGEINTERPNDSIZE2(C_DTPDT(a,b)))
#define lagrange_interp_nd_value(a,b,c,d,e,f,g) FUNCNAME_LAGRANGEINTERPNDVALUE(C_DTPDT2PITDTPITDTPIT(a,b,c,d,e,f,g))
#define lagrange_interp_nd_value2(a,b,c,d,e,f,g) FUNCNAME_LAGRANGEINTERPNDVALUE2(C_DTPDT2PITDTPITDTPIT(a,b,c,d,e,f,g))
#define order_from_level_135(a) R_INT(FUNCNAME_ORDERFROMLEVEL135(C_SINT(a)))

__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEINTERPNDSIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEINTERPNDSIZE2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CCCOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEINTERPNDGRID(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEINTERPNDGRID2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEINTERPNDVALUE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGRANGEINTERPNDVALUE2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_ORDERFROMLEVEL135(void *);

#endif
