#ifndef WRAPPER_LATIN_RANDOM_H_INCLUDED
#define WRAPPER_LATIN_RANDOM_H_INCLUDED

#define r8mat_uniform_01_new(a,b,c) FUNCNAME_R8MATUNIFORM01NEW(C_2DTPI(a,b,c))
#define latin_random_new(a,b,c) FUNCNAME_LATINRANDOMNEW(C_2DTPI(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATUNIFORM01NEW(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LATINRANDOMNEW(void *);

#endif
