#ifndef WRAPPER_LATINIZE_H_INCLUDED
#define WRAPPER_LATINIZE_H_INCLUDED

#define r8mat_latinize(a,b,c) FUNCNAME_R8MATLATINIZE(C_2DTPIT(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATLATINIZE(void *);

#endif
