#ifndef WRAPPER_LEBESGUE_H_INCLUDED
#define WRAPPER_LEBESGUE_H_INCLUDED

#define chebyshev1(a) FUNCNAME_CHEBYSHEV1(a)
#define chebyshev2(a) FUNCNAME_CHEBYSHEV2(a)
#define chebyshev3(a) FUNCNAME_CHEBYSHEV3(a)
#define chebyshev4(a) FUNCNAME_CHEBYSHEV4(a)
#define equidistant1(a) FUNCNAME_EQUIDISTANT1(a)
#define equidistant2(a) FUNCNAME_EQUIDISTANT2(a)
#define equidistant3(a) FUNCNAME_EQUIDISTANT3(a)
#define fejer1(a) FUNCNAME_FEJER1(a)
#define fejer2(a) FUNCNAME_FEJER2(a)
#define lebesgue_constant(a,b,c,d) R_DBL(FUNCNAME_LEBESGUECONSTANT(C_2DT2PIT(a,c,b,d)))
#define lebesgue_function(a,b,c,d) FUNCNAME_LEBESGUEFUNCTION(C_2DT2PIT(a,c,b,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_LEBESGUECONSTANT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CHEBYSHEV1(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CHEBYSHEV2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CHEBYSHEV3(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CHEBYSHEV4(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_EQUIDISTANT1(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_EQUIDISTANT2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_EQUIDISTANT3(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEJER1(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEJER2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEBESGUEFUNCTION(void *);

#endif
