#ifndef WRAPPER_LEGENDRE_POLYNOMIAL_H_INCLUDED
#define WRAPPER_LEGENDRE_POLYNOMIAL_H_INCLUDED

#define p_integral(a) R_INT(FUNCNAME_PINTEGRAL(C_SUSHRT(a)))
#define p_quadrature_rule(a,b,c) R_UCHR(FUNCNAME_PQUADRATURERULE(C_DT2PIT(a,b,c)))
#define p_polynomial_zeros(a,b) R_UCHR(FUNCNAME_PPOLYNOMIALZEROS(C_DTPIT(a,b)))
#define p_polynomial_prime(a,b) R_DBL(FUNCNAME_PPOLYNOMIALPRIME(C_DTIT(a,b)))
#define p_polynomial_coefficients(a,b) R_UCHR(FUNCNAME_PPOLYNOMIALCOEFFICIENTS(C_DTPIT(a,b)))
#define legendre_function_q_values(a,b,c,d) FUNCNAME_LEGENDREFUNCTIONQVALUES(C_2PDT2PIT(a,b,c,d))
#define p_polynomial_values(a,b,c,d) FUNCNAME_PPOLYNOMIALVALUES(C_2PDT2PIT(a,b,c,d))
#define pm_polynomial_values(a,b,c,d,e) FUNCNAME_PMPOLYNOMIALVALUES(C_3PDT2PIT(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_PQUADRATURERULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PPOLYNOMIALZEROS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PPOLYNOMIALCOEFFICIENTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PPOLYNOMIALPRIME(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PPOLYNOMIALVALUES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDREFUNCTIONQVALUES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PMPOLYNOMIALVALUES(void *);

#endif
