#ifndef WRAPPER_LINE_CVT_LLOYD_H_INCLUDED
#define WRAPPER_LINE_CVT_LLOYD_H_INCLUDED

#define line_ccvt_lloyd_step(a,b,c,d) FUNCNAME_LINECCVTLLOYDSTEP(C_DT2ITPIT(a,b,c,d))
#define line_cvt_energy(a,b,c,d) R_DBL(FUNCNAME_LINECVTENERGY(C_DT2ITPIT(a,b,c,d)))

__MATHSUITE __JBURKARDT void * FUNCNAME_LINECCVTLLOYDSTEP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LINECVTENERGY(void *);

#endif
