#ifndef WRAPPER_LINE_NCO_RULE_H_INCLUDED
#define WRAPPER_LINE_NCO_RULE_H_INCLUDED

#define line_nco_rule(a,b,c,d,e) FUNCNAME_LINENCORULE(C_DT2IT2PIT(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_LINENCORULE(void *);

#endif
