#ifndef WRAPPER_MONOMIAL_H_INCLUDED
#define WRAPPER_MONOMIAL_H_INCLUDED

#define mono_between_enum(a,b,c) R_USHRT(FUNCNAME_MONOBETWEENENUM(C_PUSHRT3(a,b,c)))
#define mono_between_next_grevlex(a,b,c,d) FUNCNAME_MONOBETWEENNEXTGREVLEX(C_3DTPI(a,b,c,d))
#define mono_between_next_grlex(a,b,c,d) FUNCNAME_MONOBETWEENNEXTGRLEX(C_3DTPI(a,b,c,d))
#define mono_between_random(a,b,c,d,e) FUNCNAME_MONOBETWEENRANDOM(C_3DTPIPDT(a,b,c,d,e))
#define mono_next_grevlex(a,b) FUNCNAME_MONONEXTGREVLEX(C_DTPI(a,b))
#define mono_next_grlex(a,b) FUNCNAME_MONONEXTGRLEX(C_DTPI(a,b))
#define mono_rank_grlex(a,b) R_USHRT(FUNCNAME_MONORANKGRLEX(C_DTPI(a,b)))
#define mono_total_enum(a,b) R_USHRT(FUNCNAME_MONOTOTALENUM(C_PUSHRT2(a,b)))
#define mono_total_next_grevlex(a,b,c) FUNCNAME_MONOTOTALNEXTGREVLEX(C_2DTPI(a,b,c))
#define mono_total_next_grlex(a,b,c) FUNCNAME_MONOTOTALNEXTGRLEX(C_2DTPI(a,b,c))
#define mono_total_random(a,b,c,d) FUNCNAME_MONOTOTALRANDOM(C_2DTPIPDT(a,b,c,d))
#define mono_unrank_grlex(a,b) FUNCNAME_MONOUNRANKGRLEX(C_PUSHRT2(a,b))
#define mono_upto_enum(a,b) R_USHRT(FUNCNAME_MONOUPTOENUM(C_PUSHRT2(a,b)))
#define mono_upto_next_grevlex(a,b,c) FUNCNAME_MONOUPTONEXTGREVLEX(C_2DTPI(a,b,c))
#define mono_upto_next_grlex(a,b,c) FUNCNAME_MONOUPTONEXTGRLEX(C_2DTPI(a,b,c))
#define mono_upto_random(a,b,c,d) FUNCNAME_MONOUPTORANDOM(C_2DTPIPDT(a,b,c,d))
#define mono_value(a,b,c,d) FUNCNAME_MONOVALUE(C_2DTPIPIT(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_MONOBETWEENNEXTGREVLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOBETWEENNEXTGRLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONONEXTGREVLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONONEXTGRLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONORANKGRLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOTOTALNEXTGREVLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOTOTALNEXTGRLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOUPTONEXTGREVLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOUPTONEXTGRLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOBETWEENRANDOM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOTOTALRANDOM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOUNRANKGRLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOUPTORANDOM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOVALUE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOTOTALENUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOUPTOENUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_MONOBETWEENENUM(void *);

#endif
