#ifndef WRAPPER_NEAREST_INTERP_1D_H_INCLUDED
#define WRAPPER_NEAREST_INTERP_1D_H_INCLUDED

#define nearest_interp_1d(a,b,c,d,e) FUNCNAME_NEARESTINTERP1D(C_2DT3PIT(a,d,b,c,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_NEARESTINTERP1D(void *);

#endif

