#ifndef WRAPPER_NEWTON_INTERP_1D_H_INCLUDED
#define WRAPPER_NEWTON_INTERP_1D_H_INCLUDED

#define newton_coef_1d(a,b,c) FUNCNAME_NEWTONCOEF1D(C_DT2PIT(a,b,c))
#define newton_value_1d(a,b,c,d,e) FUNCNAME_NEWTONVALUE1D(C_2DT3PIT(a,d,b,c,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_NEWTONCOEF1D(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NEWTONVALUE1D(void *);

#endif
