#ifndef WRAPPER_PADUA_H_INCLUDED
#define WRAPPER_PADUA_H_INCLUDED

#define padua_points_set(a,b,c) FUNCNAME_PADUAPOINTSSET(C_DT2PIT(a,b,c))
#define padua_points(a) FUNCNAME_PADUAPOINTS(C_SUSHRT(a))
#define padua_weights_set(a) FUNCNAME_PADUAWEIGHTSSET(C_SUSHRT(a))
#define padua_weights(a) FUNCNAME_PADUAWEIGHTS(C_SUSHRT(a))

__MATHSUITE __JBURKARDT void * FUNCNAME_PADUAPOINTSSET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PADUAPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PADUAWEIGHTSSET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PADUAWEIGHTS(void *);

#endif
