#ifndef WRAPPER_PARTITION_PROBLEM_H_INCLUDED
#define WRAPPER_PARTITION_PROBLEM_H_INCLUDED

#define partition_brute(a,b,c,d) FUNCNAME_PARTITIONBRUTE(C_DT3PI(a,b,c,d))
#define partition_count(a,b) R_USHRT(FUNCNAME_PARTITIONCOUNT(C_DTPI(a,b)))
#define partition_subset_next(a,b,c) FUNCNAME_PARTITIONSUBSETNEXT(C_DT2PI(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_PARTITIONBRUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PARTITIONCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PARTITIONSUBSETNEXT(void *);

#endif

