#ifndef WRAPPER_PATTERSON_RULE_H_INCLUDED
#define WRAPPER_PATTERSON_RULE_H_INCLUDED

#define patterson_set(a,b,c) FUNCNAME_PATTERSONSET(C_DT2PIT(a,b,c))

__MATHSUITE __JBURKARDT void * FUNCNAME_PATTERSONSET(void *);

#endif
