#ifndef WRAPPER_PDFLIB_H_INCLUDED
#define WRAPPER_PDFLIB_H_INCLUDED

#define r8_gamma_log(a) R_DBL(FUNCNAME_R8GAMMALOG(C_SDBL(a)))
#define r8_chi_pdf(a,b) R_DBL(FUNCNAME_R8CHIPDF(C_PDBL2(a,b)))
#define r8_exponential_pdf(a,b) R_DBL(FUNCNAME_R8EXPONENTIALPDF(C_PDBL2(a,b)))
#define r8_exponential_01_pdf(a) R_DBL(FUNCNAME_R8EXPONENTIAL01PDF(C_SDBL(a)))
#define r8_invchi_pdf(a,b) R_DBL(FUNCNAME_R8INVCHIPDF(C_PDBL2(a,b)))
#define r8_normal_pdf(a,b,c) R_DBL(FUNCNAME_R8NORMALPDF(C_PDBL3(a,b,c)))
#define r8_scinvchi_pdf(a,b,c) R_DBL(FUNCNAME_R8SCINVCHIPDF(C_PDBL3(a,b,c)))
#define r8_uniform_pdf(a,b,c) R_DBL(FUNCNAME_R8UNIFORMPDF(C_PDBL3(a,b,c)))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8GAMMALOG(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8EXPONENTIAL01PDF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8CHIPDF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8EXPONENTIALPDF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8INVCHIPDF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8NORMALPDF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8SCINVCHIPDF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8UNIFORMPDF(void *);

#endif
