#ifndef WRAPPER_PIECEWISE_LINEAR_PRODUCT_INTEGRAL_H_INCLUDED
#define WRAPPER_PIECEWISE_LINEAR_PRODUCT_INTEGRAL_H_INCLUDED

#define piecewise_linear_product_integral(a,b,c,d,e,f,g,h) R_DBL(FUNCNAME_PIECEWISELINEARPRODUCTINTEGRAL(C_2DT4PIT2IT(c,f,d,e,g,h,a,b)))

__MATHSUITE __JBURKARDT void * FUNCNAME_PIECEWISELINEARPRODUCTINTEGRAL(void *);

#endif
