#ifndef WRAPPER_POLYGON_GRID_H_INCLUDED
#define WRAPPER_POLYGON_GRID_H_INCLUDED

#define polygon_grid_points(a,b,c,d) FUNCNAME_POLYGONGRIDPOINTS(C_3DTPIT(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_POLYGONGRIDPOINTS(void *);

#endif
