#ifndef WRAPPER_POWER_METHOD_H_INCLUDED
#define WRAPPER_POWER_METHOD_H_INCLUDED

#define power_method(a,b,c,d,e,f,g) FUNCNAME_POWERMETHOD(C_DT2PITDTITPITPDT(a,b,c,d,e,f,g))

__MATHSUITE __JBURKARDT void * FUNCNAME_POWERMETHOD(void *);

#endif
