#ifndef WRAPPER_PYRAMID_EXACTNESS_H_INCLUDED
#define WRAPPER_PYRAMID_EXACTNESS_H_INCLUDED

#define pyra_unit_monomial(a) R_DBL(FUNCNAME_PYRAUNITMONOMIAL(a))

__MATHSUITE __JBURKARDT void * FUNCNAME_PYRAUNITMONOMIAL(void *);

#endif
