#ifndef WRAPPER_PYRAMID_GRID_H_INCLUDED
#define WRAPPER_PYRAMID_GRID_H_INCLUDED

#define pyramid_unit_grid(a,b) FUNCNAME_PYRAMIDUNITGRID(C_PUSHRT2(a,b))
#define pyramid_unit_vertices(a,b,c,d,e) FUNCNAME_PYRAMIDUNITVERTICES(C_PPDBL5(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_PYRAMIDUNITVERTICES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PYRAMIDUNITGRID(void *);

#endif
