#ifndef WRAPPER_SGMGA_H_INCLUDED
#define WRAPPER_SGMGA_H_INCLUDED

#define r8vec_copy(a,b,c) FUNCNAME_R8VECCOPY(C_DT2PIT(a,b,c))
#define binary_vector_next(a,b) FUNCNAME_BINARYVECTORNEXT(C_DTPI(a,b))
#define vec_colex_next3(a,b,c,d) FUNCNAME_VECCOLEXNEXT3(C_DT2PIPB(a,b,c,d))
#define point_unique_index(a,b,c,d,e,f) FUNCNAME_POINTUNIQUEINDEX(C_3DTPIT2PI(a,b,d,c,e,f))
#define clenshaw_curtis_compute_weights(a,b) FUNCNAME_CLENSHAWCURTISCOMPUTEWEIGHTS(C_DTPIT(a,b))
#define fejer2_compute_weights(a,b) FUNCNAME_FEJER2COMPUTEWEIGHTS(C_DTPIT(a,b))
#define fejer2_compute_weights_np(a,b,c,d) FUNCNAME_FEJER2COMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define gen_hermite_compute_weights(a,b,c) FUNCNAME_GENHERMITECOMPUTEWEIGHTS(C_DTPITIT(a,c,b))
#define gen_hermite_compute_weights_np(a,b,c,d) FUNCNAME_GENHERMITECOMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define gen_laguerre_compute_weights(a,b,c) FUNCNAME_GENLAGUERRECOMPUTEWEIGHTS(C_DTPITIT(a,c,b))
#define gen_laguerre_compute_weights_np(a,b,c,d) FUNCNAME_GENLAGUERRECOMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define hermite_compute_weights(a,b) FUNCNAME_HERMITECOMPUTEWEIGHTS(C_DTPIT(a,b))
#define hermite_compute_weights_np(a,b,c,d) FUNCNAME_HERMITECOMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define jacobi_compute_weights(a,b,c,d) FUNCNAME_JACOBICOMPUTEWEIGHTS(C_DT2ITPIT(a,b,c,d))
#define jacobi_compute_weights_np(a,b,c,d) FUNCNAME_JACOBICOMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define laguerre_compute_weights(a,b) FUNCNAME_LAGUERRECOMPUTEWEIGHTS(C_DTPIT(a,b))
#define laguerre_compute_weights_np(a,b,c,d) FUNCNAME_LAGUERRECOMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define legendre_compute_weights(a,b) FUNCNAME_LEGENDRECOMPUTEWEIGHTS(C_DTPIT(a,b))
#define legendre_compute_weights_np(a,b,c,d) FUNCNAME_LEGENDRECOMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define clenshaw_curtis_compute_weights_np(a,b,c,d) FUNCNAME_CLENSHAWCURTISCOMPUTEWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define fejer2_compute(a,b,c) FUNCNAME_FEJER2COMPUTE(C_DT2PIT(a,b,c))
#define fejer2_compute_points(a,b) FUNCNAME_FEJER2COMPUTEPOINTS(C_DTPIT(a,b))
#define fejer2_compute_points_np(a,b,c,d) FUNCNAME_FEJER2COMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define patterson_lookup_weights(a,b) FUNCNAME_PATTERSONLOOKUPWEIGHTS(C_DTPIT(a,b))
#define patterson_lookup_weights_np(a,b,c,d) FUNCNAME_PATTERSONLOOKUPWEIGHTSNP(C_2DT2PIT(a,b,c,d))
#define patterson_lookup(a,b,c) FUNCNAME_PATTERSONLOOKUP(C_DT2PIT(a,b,c))
#define patterson_lookup_points(a,b) FUNCNAME_PATTERSONLOOKUPPOINTS(C_DTPIT(a,b))
#define patterson_lookup_points_np(a,b,c,d) FUNCNAME_PATTERSONLOOKUPPOINTSNP(C_2DT2PIT(a,b,c,d))
#define jacobi_compute(a,b,c,d,e) FUNCNAME_JACOBICOMPUTE(C_DT2IT2PIT(a,b,c,d,e))
#define jacobi_compute_points(a,b,c,d) FUNCNAME_JACOBICOMPUTEPOINTS(C_DT2ITPIT(a,b,c,d))
#define jacobi_compute_points_np(a,b,c,d) FUNCNAME_JACOBICOMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define gen_laguerre_compute(a,b,c,d) FUNCNAME_GENLAGUERRECOMPUTE(C_DTIT2PIT(a,b,c,d))
#define gen_laguerre_compute_points(a,b,c) FUNCNAME_GENLAGUERRECOMPUTEPOINTS(C_DTPITIT(a,c,b))
#define gen_laguerre_compute_points_np(a,b,c,d) FUNCNAME_GENLAGUERRECOMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define laguerre_compute(a,b,c) FUNCNAME_LAGUERRECOMPUTE(C_DT2PIT(a,b,c))
#define laguerre_compute_points(a,b) FUNCNAME_LAGUERRECOMPUTEPOINTS(C_DTPIT(a,b))
#define laguerre_compute_points_np(a,b,c,d) FUNCNAME_LAGUERRECOMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define hermite_compute(a,b,c) FUNCNAME_HERMITECOMPUTE(C_DT2PIT(a,b,c))
#define hermite_compute_points(a,b) FUNCNAME_HERMITECOMPUTEPOINTS(C_DTPIT(a,b))
#define hermite_compute_points_np(a,b,c,d) FUNCNAME_HERMITECOMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define gen_hermite_compute(a,b,c,d) FUNCNAME_GENHERMITECOMPUTE(C_DTIT2PIT(a,b,c,d))
#define gen_hermite_compute_points(a,b,c) FUNCNAME_GENHERMITECOMPUTEPOINTS(C_DTPITIT(a,c,b))
#define gen_hermite_compute_points_np(a,b,c,d) FUNCNAME_GENHERMITECOMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define legendre_compute(a,b,c) FUNCNAME_LEGENDRECOMPUTE(C_DT2PIT(a,b,c))
#define legendre_compute_points(a,b) FUNCNAME_LEGENDRECOMPUTEPOINTS(C_DTPIT(a,b))
#define legendre_compute_points_np(a,b,c,d) FUNCNAME_LEGENDRECOMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define clenshaw_curtis_compute_points(a,b) FUNCNAME_CLENSHAWCURTISCOMPUTEPOINTS(C_DTPIT(a,b))
#define clenshaw_curtis_compute_points_np(a,b,c,d) FUNCNAME_CLENSHAWCURTISCOMPUTEPOINTSNP(C_2DT2PIT(a,b,c,d))
#define sgmga_aniso_normalize(a,b,c) FUNCNAME_SGMGAANISONORMALIZE(C_2DTPIT(a,b,c))
#define sgmga_importance_to_aniso(a,b,c) FUNCNAME_SGMGAIMPORTANCETOANISO(C_DT2PIT(a,b,c))
#define sgmga_vcn(a,b,c,d,e,f,g) FUNCNAME_SGMGAVCN(C_DTPIT2PI2ITPB(a,b,c,d,e,f,g))
#define sgmga_vcn_coef(a,b,c,d,e,f) R_DBL(FUNCNAME_SGMGAVCNCOEF(C_DTPIT2PI2IT(a,b,c,d,e,f)))
#define sgmga_vcn_ordered(a,b,c,d,e,f,g) FUNCNAME_SGMGAVCNORDERED(C_DTPIT2PI2ITPB(a,b,c,d,e,f,g))

__MATHSUITE __JBURKARDT void * FUNCNAME_BINARYVECTORNEXT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_VECCOLEXNEXT3(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_POINTUNIQUEINDEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CLENSHAWCURTISCOMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CLENSHAWCURTISCOMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEJER2COMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEJER2COMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PATTERSONLOOKUPWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PATTERSONLOOKUPWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENHERMITECOMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENHERMITECOMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENLAGUERRECOMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENLAGUERRECOMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITECOMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITECOMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_JACOBICOMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_JACOBICOMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGUERRECOMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGUERRECOMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDRECOMPUTEWEIGHTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDRECOMPUTEWEIGHTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEJER2COMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEJER2COMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEJER2COMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PATTERSONLOOKUP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PATTERSONLOOKUPPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_PATTERSONLOOKUPPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_JACOBICOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_JACOBICOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_JACOBICOMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENLAGUERRECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENLAGUERRECOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENLAGUERRECOMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGUERRECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGUERRECOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LAGUERRECOMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITECOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_HERMITECOMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENHERMITECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENHERMITECOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_GENHERMITECOMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDRECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDRECOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGENDRECOMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CLENSHAWCURTISCOMPUTEPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CLENSHAWCURTISCOMPUTEPOINTSNP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SGMGAANISONORMALIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SGMGAIMPORTANCETOANISO(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SGMGAVCN(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SGMGAVCNCOEF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SGMGAVCNORDERED(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECCOPY(void *);

#endif
