#ifndef WRAPPER_SHEPARD_INTERP_ND_H_INCLUDED
#define WRAPPER_SHEPARD_INTERP_ND_H_INCLUDED

#define shepard_interp_nd(a,b,c,d,e,f,g) FUNCNAME_SHEPARDINTERPND(C_2DT2PITITDTPIT(a,b,c,d,e,f,g))

__MATHSUITE __JBURKARDT void * FUNCNAME_SHEPARDINTERPND(void *);

#endif
