#ifndef WRAPPER_SHEPARD_INTERP_1D_H_INCLUDED
#define WRAPPER_SHEPARD_INTERP_1D_H_INCLUDED

#define shepard_basis_1d(a,b,c,d,e) FUNCNAME_SHEPARDBASIS1D(C_IT2DT2PIT(c,d,a,e,b))
#define shepard_value_1d(a,b,c,d,e,f) FUNCNAME_SHEPARDVALUE1D(C_DT2PITITDTPIT(a,b,c,d,e,f))

__MATHSUITE __JBURKARDT void * FUNCNAME_SHEPARDBASIS1D(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SHEPARDVALUE1D(void *);

#endif
