#ifndef WRAPPER_SIMPLEX_GRID_H_INCLUDED
#define WRAPPER_SIMPLEX_GRID_H_INCLUDED

#define ksub_random_new(a,b,c) FUNCNAME_KSUBRANDOMNEW(C_2DTPI(a,b,c))
#define comp_random_new(a,b,c) FUNCNAME_COMPRANDOMNEW(C_2DTPI(a,b,c))
#define simplex_grid_index_all(a,b,c) FUNCNAME_SIMPLEXGRIDINDEXALL(C_PUSHRT3(a,b,c))
#define simplex_grid_index_next(a,b,c) FUNCNAME_SIMPLEXGRIDINDEXNEXT(C_2DTPDT(a,b,c))
#define simplex_grid_index_sample(a,b,c) FUNCNAME_SIMPLEXGRIDINDEXSAMPLE(C_2DTPI(a,b,c))
#define simplex_grid_index_to_point(a,b,c,d,e) FUNCNAME_SIMPLEXGRIDINDEXTOPOINT(C_3DTPIPIT(a,b,c,d,e))
#define simplex_grid_sie(a,b) R_USHRT(FUNCNAME_SIMPLEXGRIDSIZE(C_PUSHRT2(a,b)))

__MATHSUITE __JBURKARDT void * FUNCNAME_SIMPLEXGRIDINDEXNEXT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_KSUBRANDOMNEW(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_COMPRANDOMNEW(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SIMPLEXGRIDINDEXALL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SIMPLEXGRIDINDEXSAMPLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SIMPLEXGRIDINDEXTOPOINT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SIMPLEXGRIDSIZE(void *);

#endif
