#ifndef WRAPPER_SNAKES_AND_LADDERS_H_INCLUDED
#define WRAPPER_SNAKES_AND_LADDERS_H_INCLUDED

#define snakes() FUNCNAME_SNAKES(NULL)

__MATHSUITE __JBURKARDT void * FUNCNAME_SNAKES(void *);

#endif
