#ifndef WRAPPER_SPARSE_INTERP_ND_H_INCLUDED
#define WRAPPER_SPARSE_INTERP_ND_H_INCLUDED

#define smolyak_coefficients(a,b,c,d) FUNCNAME_SMOLYAKCOEFFICIENTS(C_2DT2PI(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_SMOLYAKCOEFFICIENTS(void *);

#endif
