#ifndef WRAPPER_SPHERE_INTEGRALS_H_INCLUDED
#define WRAPPER_SPHERE_INTEGRALS_H_INCLUDED

#define sphere01_monomial_integral(a) R_DBL(FUNCNAME_SPHERE01MONOMIALINTEGRAL(a))
#define sphere01_sample(a,b) FUNCNAME_SPHERE01SAMPLE(C_DTPI(a,b))
#define sphere01_monomial_quadrature(a,b,c,d,e) R_DBL(FUNCNAME_SPHERE01MONOMIALQUADRATURE(C_DTPITDTPIPIT(a,b,c,d,e)))

__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01MONOMIALINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01MONOMIALQUADRATURE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01SAMPLE(void *);

#endif
