#ifndef WRAPPER_SPHERE_FIBONACCI_GRID_H_INCLUDED
#define WRAPPER_SPHERE_FIBONACCI_GRID_H_INCLUDED

#define sphere_fibonacci_grid_points(a) FUNCNAME_SPHEREFIBONACCIGRIDPOINTS(C_SUSHRT(a))

__MATHSUITE __JBURKARDT void * FUNCNAME_SPHEREFIBONACCIGRIDPOINTS(void *);

#endif
