#ifndef WRAPPER_SPHERE_QUAD_H_INCLUDED
#define WRAPPER_SPHERE_QUAD_H_INCLUDED

#define sphere01_quad_mc_size(a) R_USHRT(FUNCNAME_SPHERE01QUADMCSIZE(C_SDBL(a)))
#define sphere01_triangle_angles_to_area(a,b,c) R_DBL(FUNCNAME_SPHERE01TRIANGLEANGLESTOAREA(C_PDBL3(a,b,c)))
#define sphere01_triangle_project(a,b,c,d,e,f) FUNCNAME_SPHERE01TRIANGLEPROJECTS(C_3DT3PIT(d,e,f,a,b,c))
#define sphere01_triangle_project2(a,b,c,d,e,f) FUNCNAME_SPHERE01TRIANGLEPROJECTS2(C_3DT3PIT(d,e,f,a,b,c))
#define sphere01_triangle_sample(a,b,c,d,e) FUNCNAME_SPHERE01TRIANGLESAMPLE(C_DT3PITPI(a,b,c,d,e))
#define sphere01_triangle_sides_to_angles(a,b,c,d,e,f) FUNCNAME_SPHERE01TRIANGLESIDESTOANGLES(C_3IT3PIT(a,b,c,d,e,f))
#define sphere01_triangle_vertices_to_angles(a,b,c,d,e,f) FUNCNAME_SPHERE01TRIANGLEVERTICESTOANGLES(C_PPDBL6(a,b,c,d,e,f))
#define sphere01_triangle_vertices_to_area(a,b,c) R_DBL(FUNCNAME_SPHERE01TRIANGLEVERTICESTOAREA(C_PPDBL3(a,b,c)))
#define sphere01_triangle_vertices_to_centroid(a,b,c) FUNCNAME_SPHERE01TRIANGLEVERTICESTOCENTROID(C_PPDBL3(a,b,c))
#define sphere01_triangle_vertices_to_midpoints(a,b,c,d,e,f) FUNCNAME_SPHERE01TRIANGLEVERTICESTOMIDPOINTS(C_PPDBL6(a,b,c,d,e,f))
#define sphere01_triangle_vertices_to_sides(a,b,c,d,e,f) FUNCNAME_SPHERE01TRIANGLEVERTICESTOSIDES(C_PPDBL6(a,b,c,d,e,f))

__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLESIDESTOANGLES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEVERTICESTOANGLES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEVERTICESTOAREA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEVERTICESTOMIDPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEVERTICESTOSIDES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEPROJECTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEPROJECTS2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLESAMPLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEVERTICESTOCENTROID(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01QUADMCSIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERE01TRIANGLEANGLESTOAREA(void *);


#endif
