#ifndef WRAPPER_SPHERE_STEREOGRAPH_H_INCLUDED
#define WRAPPER_SPHERE_STEREOGRAPH_H_INCLUDED

#define sphere_stereograph2(a,b,c,d,e) FUNCNAME_SPHERESTEREOGRAPH2(C_2DT3PIT(a,b,c,d,e))
#define sphere_stereograph2_inverse(a,b,c,d,e) FUNCNAME_SPHERESTEREOGRAPH2INVERSE(C_2DT3PIT(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERESTEREOGRAPH2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERESTEREOGRAPH2INVERSE(void *);

#endif
