#ifndef WRAPPER_SPHERE_LLT_GRID_H_INCLUDED
#define WRAPPER_SPHERE_LLT_GRID_H_INCLUDED

#define sphere_llt_grid_line_count(a,b) R_USHRT(FUNCNAME_SPHERELLTGRIDLINECOUNT(C_PUSHRT2(a,b)))
#define sphere_llt_grid_lines(a,b,c) FUNCNAME_SPHERELLTGRIDLINES(C_PUSHRT3(a,b,c))
#define sphere_llt_grid_point_count(a,b) R_USHRT(FUNCNAME_SPHERELLTGRIDPOINTCOUNT(C_PUSHRT2(a,b)))
#define sphere_llt_grid_points(a,b,c,d,e) FUNCNAME_SPHERELLTGRIDPOINTS(C_ITPIT3DT(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERELLTGRIDLINES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERELLTGRIDPOINTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERELLTGRIDLINECOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SPHERELLTGRIDPOINTCOUNT(void *);

#endif
