#ifndef WRAPPER_SQUARE_SYMQ_RULE_H_INCLUDED
#define WRAPPER_SQUARE_SYMQ_RULE_H_INCLUDED

#define squaresymq_rule_full_size(a) R_USHRT(FUNCNAME_SQUARESYMQFULLSIZE(C_SUSHRT(a)))
#define squaresymq_rule01(a,b,c) FUNCNAME_SQUARESYMQRULE01(C_DT2PIT(a,b,c))
#define squaresymq_rule02(a,b,c) FUNCNAME_SQUARESYMQRULE02(C_DT2PIT(a,b,c))
#define squaresymq_rule03(a,b,c) FUNCNAME_SQUARESYMQRULE03(C_DT2PIT(a,b,c))
#define squaresymq_rule04(a,b,c) FUNCNAME_SQUARESYMQRULE04(C_DT2PIT(a,b,c))
#define squaresymq_rule05(a,b,c) FUNCNAME_SQUARESYMQRULE05(C_DT2PIT(a,b,c))
#define squaresymq_rule06(a,b,c) FUNCNAME_SQUARESYMQRULE06(C_DT2PIT(a,b,c))
#define squaresymq_rule07(a,b,c) FUNCNAME_SQUARESYMQRULE07(C_DT2PIT(a,b,c))
#define squaresymq_rule08(a,b,c) FUNCNAME_SQUARESYMQRULE08(C_DT2PIT(a,b,c))
#define squaresymq_rule09(a,b,c) FUNCNAME_SQUARESYMQRULE09(C_DT2PIT(a,b,c))
#define squaresymq_rule10(a,b,c) FUNCNAME_SQUARESYMQRULE10(C_DT2PIT(a,b,c))
#define squaresymq_rule11(a,b,c) FUNCNAME_SQUARESYMQRULE11(C_DT2PIT(a,b,c))
#define squaresymq_rule12(a,b,c) FUNCNAME_SQUARESYMQRULE12(C_DT2PIT(a,b,c))
#define squaresymq_rule13(a,b,c) FUNCNAME_SQUARESYMQRULE13(C_DT2PIT(a,b,c))
#define squaresymq_rule14(a,b,c) FUNCNAME_SQUARESYMQRULE14(C_DT2PIT(a,b,c))
#define squaresymq_rule15(a,b,c) FUNCNAME_SQUARESYMQRULE15(C_DT2PIT(a,b,c))
#define squaresymq_rule16(a,b,c) FUNCNAME_SQUARESYMQRULE16(C_DT2PIT(a,b,c))
#define squaresymq_rule17(a,b,c) FUNCNAME_SQUARESYMQRULE17(C_DT2PIT(a,b,c))
#define squaresymq_rule18(a,b,c) FUNCNAME_SQUARESYMQRULE18(C_DT2PIT(a,b,c))
#define squaresymq_rule19(a,b,c) FUNCNAME_SQUARESYMQRULE19(C_DT2PIT(a,b,c))
#define squaresymq_rule20(a,b,c) FUNCNAME_SQUARESYMQRULE20(C_DT2PIT(a,b,c))
#define square_symq(a,b,c,d) FUNCNAME_SQUARESYMQ(C_2DT2PIT(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE02(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE04(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE05(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE08(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE09(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE10(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE11(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE12(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE13(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE14(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE15(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE16(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE17(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE18(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE19(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQRULE20(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQ(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARESYMQFULLSIZE(void *);

#endif

