#ifndef WRAPPER_SQUARE_INTEGRALS_H_INCLUDED
#define WRAPPER_SQUARE_INTEGRALS_H_INCLUDED

#define square01_sample(a,b) FUNCNAME_SQUARE01SAMPLE(C_DTPI(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_SQUARE01SAMPLE(void *);

#endif
