#ifndef WRAPPER_SQUARE_ARBQ_RULE_H_INCLUDED
#define WRAPPER_SQUARE_ARBQ_RULE_H_INCLUDED

#define lege2eva(a,b) FUNCNAME_LEGE2EVA(C_DTPIT(a,b))
#define llegepols1(a,b) FUNCNAME_LLEGEPOLS1(C_DTIT(a,b))
#define squarearbq_rule01(a,b,c) FUNCNAME_SQUAREARBQRULE01(C_DT2PIT(a,b,c))
#define squarearbq_rule02(a,b,c) FUNCNAME_SQUAREARBQRULE02(C_DT2PIT(a,b,c))
#define squarearbq_rule03(a,b,c) FUNCNAME_SQUAREARBQRULE03(C_DT2PIT(a,b,c))
#define squarearbq_rule04(a,b,c) FUNCNAME_SQUAREARBQRULE04(C_DT2PIT(a,b,c))
#define squarearbq_rule05(a,b,c) FUNCNAME_SQUAREARBQRULE05(C_DT2PIT(a,b,c))
#define squarearbq_rule06(a,b,c) FUNCNAME_SQUAREARBQRULE06(C_DT2PIT(a,b,c))
#define squarearbq_rule07(a,b,c) FUNCNAME_SQUAREARBQRULE07(C_DT2PIT(a,b,c))
#define squarearbq_rule08(a,b,c) FUNCNAME_SQUAREARBQRULE08(C_DT2PIT(a,b,c))
#define squarearbq_rule09(a,b,c) FUNCNAME_SQUAREARBQRULE09(C_DT2PIT(a,b,c))
#define squarearbq_rule10(a,b,c) FUNCNAME_SQUAREARBQRULE10(C_DT2PIT(a,b,c))
#define squarearbq_rule11(a,b,c) FUNCNAME_SQUAREARBQRULE11(C_DT2PIT(a,b,c))
#define squarearbq_rule12(a,b,c) FUNCNAME_SQUAREARBQRULE12(C_DT2PIT(a,b,c))
#define squarearbq_rule13(a,b,c) FUNCNAME_SQUAREARBQRULE13(C_DT2PIT(a,b,c))
#define squarearbq_rule14(a,b,c) FUNCNAME_SQUAREARBQRULE14(C_DT2PIT(a,b,c))
#define squarearbq_rule15(a,b,c) FUNCNAME_SQUAREARBQRULE15(C_DT2PIT(a,b,c))
#define squarearbq_rule16(a,b,c) FUNCNAME_SQUAREARBQRULE16(C_DT2PIT(a,b,c))
#define squarearbq_rule17(a,b,c) FUNCNAME_SQUAREARBQRULE17(C_DT2PIT(a,b,c))
#define squarearbq_rule18(a,b,c) FUNCNAME_SQUAREARBQRULE18(C_DT2PIT(a,b,c))
#define squarearbq_rule19(a,b,c) FUNCNAME_SQUAREARBQRULE19(C_DT2PIT(a,b,c))
#define squarearbq_rule20(a,b,c) FUNCNAME_SQUAREARBQRULE20(C_DT2PIT(a,b,c))
#define squarearbq_rule21(a,b,c) FUNCNAME_SQUAREARBQRULE21(C_DT2PIT(a,b,c))
#define squarearbq_rule22(a,b,c) FUNCNAME_SQUAREARBQRULE22(C_DT2PIT(a,b,c))
#define squarearbq_rule23(a,b,c) FUNCNAME_SQUAREARBQRULE23(C_DT2PIT(a,b,c))
#define squarearbq_rule24(a,b,c) FUNCNAME_SQUAREARBQRULE24(C_DT2PIT(a,b,c))
#define squarearbq_rule25(a,b,c) FUNCNAME_SQUAREARBQRULE25(C_DT2PIT(a,b,c))
#define squarearbq_rule26(a,b,c) FUNCNAME_SQUAREARBQRULE26(C_DT2PIT(a,b,c))
#define squarearbq_rule27(a,b,c) FUNCNAME_SQUAREARBQRULE27(C_DT2PIT(a,b,c))
#define squarearbq_rule28(a,b,c) FUNCNAME_SQUAREARBQRULE28(C_DT2PIT(a,b,c))
#define squarearbq_rule29(a,b,c) FUNCNAME_SQUAREARBQRULE29(C_DT2PIT(a,b,c))
#define squarearbq_rule30(a,b,c) FUNCNAME_SQUAREARBQRULE30(C_DT2PIT(a,b,c))
#define square_arbq(a,b,c,d) FUNCNAME_SQUAREARBQ(C_2DT2PIT(a,b,c,d))
#define square_arbq_size(a) R_USHRT(FUNCNAME_SQUAREARBQSIZE(C_SUSHRT(a)))

__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE02(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE04(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE05(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE08(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE09(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE10(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE11(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE12(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE13(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE14(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE15(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE16(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE17(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE18(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE19(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE20(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE21(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE22(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE23(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE24(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE25(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE26(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE27(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE28(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE29(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQRULE30(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQ(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LEGE2EVA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_LLEGEPOLS1(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SQUAREARBQSIZE(void *);


#endif
