#ifndef WRAPPER_TET_MESH_H_INCLUDED
#define WRAPPER_TET_MESH_H_INCLUDED

#define tet_mesh_neighbor_tets(a,b,c) FUNCNAME_TETMESHNEIGHBORTETS(C_2DTPI(a,b,c))
#define tet_mesh_node_order(a,b,c,d) FUNCNAME_TETMESHNODEORDER(C_3DTPI(a,b,d,c))
#define tet_mesh_order4_adj_count(a,b,c,d,e) FUNCNAME_TETMESHORDER4ADJCOUNT(C_2DT3PI(a,b,c,d,e))
#define tet_mesh_order4_adj_set(a,b,c,d,e) FUNCNAME_TETMESHORDER4ADJSET(C_3DT2PI(a,b,d,c,e))
#define tet_mesh_order4_boundary_face_count(a,b) R_USHRT(FUNCNAME_TETMESHORDER4BOUNDARYFACECOUNT(C_DTPI(a,b)))
#define tet_mesh_order4_edge_count(a,b) R_USHRT(FUNCNAME_TETMESHORDER4EDGECOUNT(C_DTPI(a,b)))
#define tet_mesh_order4_refine_compute(a,b,c,d,e,f,g,h,i) FUNCNAME_TETMESHORDER4REFINECOMPUTE(C_2DTPITPI2DTPIPITPI(a,b,c,d,e,f,g,h,i))
#define tet_mesh_order4_refine_size(a,b,c,d,e,f) FUNCNAME_TETMESHORDER4REFINESIZE(C_2DT4PI(a,b,c,d,e,f))
#define tet_mesh_order4_to_order10_compute(a,b,c,d,e,f,g,h) FUNCNAME_TETMESHORDER4TOORDER10COMPUTE(C_DTPIDTPIT2PIDTPIT(a,b,c,d,e,f,g,h))
#define tet_mesh_order4_to_order10_size(a,b,c,d,e) FUNCNAME_TETMESHORDERTOORDER10SIZE(C_2DT3PI(a,c,b,d,e))
#define tet_mesh_order10_adj_count(a,b,c,d,e) FUNCNAME_TETMESHORDER10ADJCOUNT(C_2DT3PI(a,b,c,d,e))
#define tet_mesh_order10_adj_set(a,b,c,d,e) FUNCNAME_TETMESHORDER10ADJSET(C_2DTPIIPI(a,b,c,d,e))
#define tetrahedron_order4_physical_to_reference(a,b,c,d) FUNCNAME_TETRAHEDRONORDER4PHYSICALTOREFERENCE(C_DT3PIT(b,c,d,a))

__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER4ADJCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER4BOUNDARYFACECOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER4EDGECOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER4REFINECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER4REFINESIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER4TOORDER10COMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDERTOORDER10SIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER10ADJCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONORDER4PHYSICALTOREFERENCE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHNEIGHBORTETS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHNODEORDER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER4ADJSET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETMESHORDER10ADJSET(void *);

#endif
