#ifndef WRAPPER_TETRAHEDRON_GRID_H_INCLUDED
#define WRAPPER_TETRAHEDRON_GRID_H_INCLUDED

#define tetrahedron_grid(a,b,c) FUNCNAME_TETRAHEDRONGRID(C_2DTPIT(a,c,b))
#define tetrahedron_grid_count(a) R_USHRT(FUNCNAME_TETRAHEDRONGRIDCOUNT(C_SUSHRT(a)))

__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONGRID(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONGRIDCOUNT(void *);

#endif
