#ifndef WRAPPER_TETRAHEDRON_EXACTNESS_H_INCLUDED
#define WRAPPER_TETRAHEDRON_EXACTNESS_H_INCLUDED

#define tet01_monomial_integral(a,b) R_DBL(FUNCNAME_TET01MONOMIALINTEGRAL(C_DTPI(a,b)))
#define tet01_monomial_quadrature(a,b,c,d,e) R_DBL(FUNCNAME_TET01MONOMIALQUADRATURE(C_DTPITDTPIPIT(a,b,c,d,e)))

__MATHSUITE __JBURKARDT void * FUNCNAME_TET01MONOMIALINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TET01MONOMIALQUADRATURE(void *);

#endif

