#ifndef WRAPPER_TETRAHEDRON_NCC_RULE_H_INCLUDED
#define WRAPPER_TETRAHEDRON_NCC_RULE_H_INCLUDED

#define reference_to_physical_t4(a,b,c,d) FUNCNAME_REFERENCETOPHYSICALT4(C_DT3PIT(b,c,d,a))
#define tetrahedron_ncc_degree(a) R_USHRT(FUNCNAME_TETRAHEDRONNCCDEGREE(C_SUSHRT(a)))
#define tetrahedron_ncc_order_num(a) R_USHRT(FUNCNAME_TETRAHEDRONNCCORDERNUM(C_SUSHRT(a)))
#define tetrahedron_ncc_rule(a,b,c,d) FUNCNAME_TETRAHEDRONNCCRULE(C_DTIT2PIT(a,b,c,d))
#define tetrahedron_ncc_rule_num() R_USHRT(FUNCNAME_TETRAHEDRONNCCRULENUM(NULL))
#define tetrahedron_ncc_suborder(a,b) FUNCNAME_TETRAHEDRONNCCSUBORDER(C_PUSHRT2(a,b))
#define tetrahedron_ncc_suborder_num(a) R_USHRT(FUNCNAME_TETRAHEDRONNCCSUBORDERNUM(C_SUSHRT(a)))
#define tetrahedron_ncc_subrule(a,b,c,d) FUNCNAME_TETRAHEDRONNCCSUBRULE(C_2DT2PIT(a,b,c,d))
#define tetrahedron_ncc_subrule_01(a,b,c,d,e) FUNCNAME_TETRAHEDRONNCCSUBRULE01(C_DT4PI(a,b,c,d,e))
#define tetrahedron_ncc_subrule_02(a,b,c,d,e) FUNCNAME_TETRAHEDRONNCCSUBRULE02(C_DT4PI(a,b,c,d,e))
#define tetrahedron_ncc_subrule_03(a,b,c,d,e) FUNCNAME_TETRAHEDRONNCCSUBRULE03(C_DT4PI(a,b,c,d,e))
#define tetrahedron_ncc_subrule_04(a,b,c,d,e) FUNCNAME_TETRAHEDRONNCCSUBRULE04(C_DT4PI(a,b,c,d,e))
#define tetrahedron_ncc_subrule_05(a,b,c,d,e) FUNCNAME_TETRAHEDRONNCCSUBRULE05(C_DT4PI(a,b,c,d,e))
#define tetrahedron_ncc_subrule_06(a,b,c,d,e) FUNCNAME_TETRAHEDRONNCCSUBRULE06(C_DT4PI(a,b,c,d,e))
#define tetrahedron_ncc_subrule_07(a,b,c,d,e) FUNCNAME_TETRAHEDRONNCCSUBRULE07(C_DT4PI(a,b,c,d,e))
#define tetrahedron_volume() R_DBL(FUNCNAME_TETRAHEDRONVOLUME(NULL))

__MATHSUITE __JBURKARDT void * FUNCNAME_REFERENCETOPHYSICALT4(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCRULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCRULENUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE02(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE04(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE05(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBRULE07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONVOLUME(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBORDER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCSUBORDERNUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCDEGREE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRONNCCORDERNUM(void *);


#endif
