#ifndef WRAPPER_TETRAHEDRON_INTEGRALS_H_INCLUDED
#define WRAPPER_TETRAHEDRON_INTEGRALS_H_INCLUDED

#define tetrahedron01_monomial_integral(a) R_DBL(FUNCNAME_TETRAHEDRON01MONOMIALINTEGRAL(a))
#define tetrahedron01_sample(a,b) FUNCNAME_TETRAHEDRON01SAMPLE(C_DTPI(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRON01MONOMIALINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TETRAHEDRON01SAMPLE(void *);

#endif
