#ifndef WRAPPER_TOEPLITZ_CHOLESKY_H_INCLUDED
#define WRAPPER_TOEPLITZ_CHOLESKY_H_INCLUDED

#define toep_cholesky_lower(a,b) FUNCNAME_TOEPCHOLESKYLOWER(C_DTPIT(a,b))
#define toep_cholesky_upper(a,b) FUNCNAME_TOEPCHOLESKYUPPER(C_DTPIT(a,b))
#define toeplitz_cholesky_lower(a,b) FUNCNAME_TOEPLITZCHOLESKYLOWER(C_DTPIT(a,b))
#define toeplitz_cholesky_upper(a,b) FUNCNAME_TOEPLITZCHOLESKYUPPER(C_DTPIT(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_TOEPCHOLESKYLOWER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TOEPCHOLESKYUPPER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TOEPLITZCHOLESKYLOWER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TOEPLITZCHOLESKYUPPER(void *);

#endif
