#ifndef WRAPPER_TOMS097_H_INCLUDED
#define WRAPPER_TOMS097_H_INCLUDED

#define i4mat_shortest_path(a,b) FUNCNAME_I4MATSHORTESTPATH(C_DTPI(a,b))
#define r8mat_shortest_path(a,b) FUNCNAME_R8MATSHORTESTPATH(C_DTPIT(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_I4MATSHORTESTPATH(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_R8MATSHORTESTPATH(void *);

#endif
