#ifndef WRAPPER_TRIANGLE_EXACTNESS_H_INCLUDED
#define WRAPPER_TRIANGLE_EXACTNESS_H_INCLUDED

#define triangle01_monomial_integral(a,b) R_DBL(FUNCNAME_TRIANGLE01MONOMIALINTEGRAL(C_DTPI(a,b)))
#define triangle01_monomial_quadrature(a,b,c,d,e) R_DBL(FUNCNAME_TRIANGLE01MONOMIALQUADRATURE(C_DTPITDTPIPIT(a,b,c,d,e)))

__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLE01MONOMIALINTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLE01MONOMIALQUADRATURE(void *);

#endif
