#ifndef WRAPPER_TRIANGLE_SYMQ_RULE_H_INCLUDED
#define WRAPPER_TRIANGLE_SYMQ_RULE_H_INCLUDED

#define quaenodes(a,b,c,d,e,f,g,h) FUNCNAME_QUAENODES(C_DT3PITDT3PIT(a,b,c,d,e,f,g,h))
#define quaenodes2(a,b,c,d,e,f,g,h) FUNCNAME_QUAENODES2(C_DT3PITDT3PIT(a,b,c,d,e,f,g,h))
#define quaerotate(a,b,c,d) FUNCNAME_QUAEROTATE(C_2IT2PIT(a,b,c,d))
#define quaecopy(a,b,c,d,e,f) FUNCNAME_QUAECOPY(C_DT5PIT(a,b,c,d,e,f))
#define quaequad(a,b,c,d,e) FUNCNAME_QUAEQUAD(C_3DT2PIT(a,b,e,c,d))
#define triangle_area(a,b,c) R_DBL(FUNCNAME_TRIANGLEAREA(C_PPDBL3(a,b,c)))
#define quaeinside(a,b,c) R_UCHR(FUNCNAME_QUAEINSIDE(C_2ITDT(b,c,a)))
#define quaequad0(a,b,c,d,e) FUNCNAME_QUAEQUAD0(C_2DT3PIT(a,b,c,d,e))
#define triangle_rule_compressed_size(a) R_USHRT(FUNCNAME_TRIANGLERULECOMPRESSEDSIZE(C_SUSHRT(a)))
#define triangle_rule_full_size(a) R_USHRT(FUNCNAME_TRIANGLERULEFULLSIZE(C_SUSHRT(a)))
#define triangle_rule01(a,b,c) FUNCNAME_TRIANGLERULE01(C_PPDBL3(a,b,c))
#define triangle_rule02(a,b,c) FUNCNAME_TRIANGLERULE02(C_PPDBL3(a,b,c))
#define triangle_rule03(a,b,c) FUNCNAME_TRIANGLERULE03(C_PPDBL3(a,b,c))
#define triangle_rule04(a,b,c) FUNCNAME_TRIANGLERULE04(C_PPDBL3(a,b,c))
#define triangle_rule05(a,b,c) FUNCNAME_TRIANGLERULE05(C_PPDBL3(a,b,c))
#define triangle_rule06(a,b,c) FUNCNAME_TRIANGLERULE06(C_PPDBL3(a,b,c))
#define triangle_rule07(a,b,c) FUNCNAME_TRIANGLERULE07(C_PPDBL3(a,b,c))
#define triangle_rule08(a,b,c) FUNCNAME_TRIANGLERULE08(C_PPDBL3(a,b,c))
#define triangle_rule09(a,b,c) FUNCNAME_TRIANGLERULE09(C_PPDBL3(a,b,c))
#define triangle_rule10(a,b,c) FUNCNAME_TRIANGLERULE10(C_PPDBL3(a,b,c))
#define triangle_rule11(a,b,c) FUNCNAME_TRIANGLERULE11(C_PPDBL3(a,b,c))
#define triangle_rule12(a,b,c) FUNCNAME_TRIANGLERULE12(C_PPDBL3(a,b,c))
#define triangle_rule13(a,b,c) FUNCNAME_TRIANGLERULE13(C_PPDBL3(a,b,c))
#define triangle_rule14(a,b,c) FUNCNAME_TRIANGLERULE14(C_PPDBL3(a,b,c))
#define triangle_rule15(a,b,c) FUNCNAME_TRIANGLERULE15(C_PPDBL3(a,b,c))
#define triangle_rule16(a,b,c) FUNCNAME_TRIANGLERULE16(C_PPDBL3(a,b,c))
#define triangle_rule17(a,b,c) FUNCNAME_TRIANGLERULE17(C_PPDBL3(a,b,c))
#define triangle_rule18(a,b,c) FUNCNAME_TRIANGLERULE18(C_PPDBL3(a,b,c))
#define triangle_rule19(a,b,c) FUNCNAME_TRIANGLERULE19(C_PPDBL3(a,b,c))
#define triangle_rule20(a,b,c) FUNCNAME_TRIANGLERULE20(C_PPDBL3(a,b,c))
#define triangle_rule21(a,b,c) FUNCNAME_TRIANGLERULE21(C_PPDBL3(a,b,c))
#define triangle_rule22(a,b,c) FUNCNAME_TRIANGLERULE22(C_PPDBL3(a,b,c))
#define triangle_rule23(a,b,c) FUNCNAME_TRIANGLERULE23(C_PPDBL3(a,b,c))
#define triangle_rule24(a,b,c) FUNCNAME_TRIANGLERULE24(C_PPDBL3(a,b,c))
#define triangle_rule25(a,b,c) FUNCNAME_TRIANGLERULE25(C_PPDBL3(a,b,c))
#define triangle_rule26(a,b,c) FUNCNAME_TRIANGLERULE26(C_PPDBL3(a,b,c))
#define triangle_rule27(a,b,c) FUNCNAME_TRIANGLERULE27(C_PPDBL3(a,b,c))
#define triangle_rule28(a,b,c) FUNCNAME_TRIANGLERULE28(C_PPDBL3(a,b,c))
#define triangle_rule29(a,b,c) FUNCNAME_TRIANGLERULE29(C_PPDBL3(a,b,c))
#define triangle_rule30(a,b,c) FUNCNAME_TRIANGLERULE30(C_PPDBL3(a,b,c))
#define triangle_rule31(a,b,c) FUNCNAME_TRIANGLERULE31(C_PPDBL3(a,b,c))
#define triangle_rule32(a,b,c) FUNCNAME_TRIANGLERULE32(C_PPDBL3(a,b,c))
#define triangle_rule33(a,b,c) FUNCNAME_TRIANGLERULE33(C_PPDBL3(a,b,c))
#define triangle_rule34(a,b,c) FUNCNAME_TRIANGLERULE34(C_PPDBL3(a,b,c))
#define triangle_rule35(a,b,c) FUNCNAME_TRIANGLERULE35(C_PPDBL3(a,b,c))
#define triangle_rule36(a,b,c) FUNCNAME_TRIANGLERULE36(C_PPDBL3(a,b,c))
#define triangle_rule37(a,b,c) FUNCNAME_TRIANGLERULE37(C_PPDBL3(a,b,c))
#define triangle_rule38(a,b,c) FUNCNAME_TRIANGLERULE38(C_PPDBL3(a,b,c))
#define triangle_rule39(a,b,c) FUNCNAME_TRIANGLERULE39(C_PPDBL3(a,b,c))
#define triangle_rule40(a,b,c) FUNCNAME_TRIANGLERULE40(C_PPDBL3(a,b,c))
#define triangle_rule41(a,b,c) FUNCNAME_TRIANGLERULE41(C_PPDBL3(a,b,c))
#define triangle_rule42(a,b,c) FUNCNAME_TRIANGLERULE42(C_PPDBL3(a,b,c))
#define triangle_rule43(a,b,c) FUNCNAME_TRIANGLERULE43(C_PPDBL3(a,b,c))
#define triangle_rule44(a,b,c) FUNCNAME_TRIANGLERULE44(C_PPDBL3(a,b,c))
#define triangle_rule45(a,b,c) FUNCNAME_TRIANGLERULE45(C_PPDBL3(a,b,c))
#define triangle_rule46(a,b,c) FUNCNAME_TRIANGLERULE46(C_PPDBL3(a,b,c))
#define triangle_rule47(a,b,c) FUNCNAME_TRIANGLERULE47(C_PPDBL3(a,b,c))
#define triangle_rule48(a,b,c) FUNCNAME_TRIANGLERULE48(C_PPDBL3(a,b,c))
#define triangle_rule49(a,b,c) FUNCNAME_TRIANGLERULE49(C_PPDBL3(a,b,c))
#define triangle_rule50(a,b,c) FUNCNAME_TRIANGLERULE50(C_PPDBL3(a,b,c))
#define simplex_to_triangle(a,b,c,d) FUNCNAME_SIMPLEXTOTRIANGLE(C_PPDBL4(a,b,c,d))
#define triangle_to_ref(a,b,c,d) FUNCNAME_TRIANGLETOREF(C_PPDBL4(a,b,c,d))
#define triangle_to_simplex(a,b,c,d) FUNCNAME_TRIANGLETOSIMPLEX(C_PPDBL4(a,b,c,d))
#define trianmap(a,b,c,d,e,f) FUNCNAME_TRIANMAP(C_DT5PIT(a,b,c,d,e,f))
#define triasimp(a,b,c,d) FUNCNAME_TRIASIMP(C_2IT2PIT(a,b,c,d))
#define triasymq(a,b,c,d,e,f,g) FUNCNAME_TRIASYMQ(C_DT5PIT(a,b,c,d,e,f,g))

__MATHSUITE __JBURKARDT void * FUNCNAME_QUAENODES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_QUAENODES2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_QUAEROTATE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_QUAECOPY(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_QUAEQUAD(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEAREA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE02(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE04(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE05(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE08(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE09(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE10(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE11(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE12(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE13(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE14(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE15(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE16(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE17(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE18(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE19(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE20(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE21(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE22(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE23(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE24(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE25(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE26(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE27(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE28(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE29(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE30(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE31(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE32(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE33(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE34(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE35(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE36(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE37(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE38(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE39(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE40(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE41(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE42(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE43(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE44(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE45(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE46(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE47(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE48(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE49(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULE50(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANMAP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIASIMP(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIASYMQ(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_SIMPLEXTOTRIANGLE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLETOREF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLETOSIMPLEX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULECOMPRESSEDSIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLERULEFULLSIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_QUAEINSIDE(void *);

#endif
