#ifndef WRAPPER_TRIANGLE_GRID_H_INCLUDED
#define WRAPPER_TRIANGLE_GRID_H_INCLUDED

#define triangle_grid(a,b) FUNCNAME_TRIANGLEGRID(C_DTPIT(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEGRID(void *);

#endif
