#ifndef WRAPPER_TRIANGULATION_H_INCLUDED
#define WRAPPER_TRIANGULATION_H_INCLUDED

#define triangle_order3_reference_to_physical(a,b,c,d) FUNCNAME_TRIANGLEORDER3REFERENCETOPHYSICAL(C_DT3PIT(b,c,d,a))
#define triangle_order3_physical_to_reference(a,b,c,d) FUNCNAME_TRIANGLEORDER3PHYSICALTOREFERENCE(C_DT3PIT(b,c,d,a))
#define alpha_measure(a,b,c,d,e,f,g,h) FUNCNAME_ALPHAMEASURE(C_DTPIT2DTPI3PIT(a,b,c,d,e,f,g,h))
#define area_measure(a,b,c,d,e,f,g,h,i,j) FUNCNAME_AREAMEASURE(C_DTPIT2DTPI5PIT(a,b,c,d,e,f,g,h,i,j))
#define bandwidth(a,b,c,d,e,f) FUNCNAME_BANDWIDTH(C_2DTPI3PDT(a,b,c,d,e,f))
#define delaunay_swap_test(a) R_UCHR(FUNCNAME_DELAUNAYSWAPTEST(a))
#define ns_adj_col_set(a,b,c,d,e,f,g,h,i) R_INT(FUNCNAME_NSADJCOLSET(C_3DT6PI(a,b,c,d,e,f,g,h,i)))
#define ns_adj_count(a,b,c,d,e,f,g,h,i) R_USHRT(FUNCNAME_NSADJCOUNT(C_3DT6PI(a,b,c,d,e,f,g,h,i)))
#define ns_adj_insert(a,b,c,d,e,f) FUNCNAME_NSADJINSERT(C_2DTPI2DTPI(a,b,e,c,d,f))
#define ns_adj_row_set(a,b,c,d,e,f,g,h,i,j,k) FUNCNAME_NSADJROWSET(C_3I5PIDT2PI(a,b,c,d,e,f,g,h,i,j,k))
#define q_measure(a,b,c,d,e,f,g,h,i) FUNCNAME_QMEASURE(C_DTPIT2DTPI4PIT(a,b,c,d,e,f,g,h,i))
#define quad_convex_random(a,b) FUNCNAME_QUADCONVEXRANDOM(C_PIPIT(a,b))
#define points_delaunay_naive_2d(a,b,c) FUNCNAME_POINTSDELAUNAYNAIVE2D(C_DTPITPDT(a,b,c))
#define triangulation_area(a,b,c,d,e) R_DBL(FUNCNAME_TRIANGULATIONAREA(C_3DTPIPIT(a,c,d,e,b)))
#define triangulation_areas(a,b,c,d,e,f) R_DBL(FUNCNAME_TRIANGULATIONAREAS(C_DTPIT2DTPI(a,b,c,d,e,f)))
#define triangulation_delaunay_discrepancy_compute(a,b,c,d,e,f,g,h,i,j) R_DBL(FUNCNAME_TRIANGULATIONDELAUNAYDISCREPANCYCOMPUTE(C_DTPIT2DT2PIPITPIPITPI(a,b,c,d,e,f,g,h,i,j)))
#define triangulation_neighbor_elements(a,b,c) FUNCNAME_TRIANGULATIONNEIGHBORELEMENTS(C_2DTPI(a,b,c))
#define triangulation_node_order(a,b,c,d) FUNCNAME_TRIANGULATIONNODEORDER(C_2DTPII(a,b,c,d))
#define triangulation_order3_adj_count(a,b,c,d,e) R_USHRT(FUNCNAME_TRIANGULATIONORDER3ADJCOUNT(C_2DT3PI(a,b,c,d,e)))
#define triangulation_order3_adj_set(a,b,c,d,e,f) FUNCNAME_TRIANGULATIONORDER3ADJSET(C_2DT2PIDTPI(a,b,c,d,e,f))
#define triangulation_order3_adj_set2(a,b,c,d,e,f,g,h) FUNCNAME_TRIANGULATIONORDER3ADJSET2(C_2DT2PIDTPI(a,b,c,d,e,f,g,h))
#define triangulation_order3_adjacency(a,b,c) FUNCNAME_TRIANGULATIONORDER3ADJACENCY(C_2DTPI(a,b,c))
#define triangulation_order3_boundary_edge_count(a,b) R_USHRT(FUNCNAME_TRIANGULATIONORDER3BOUNDARYEDGECOUNT(C_DTPI(a,b)))
#define triangulation_order3_boundary_edge_count_euler(a,b,c) R_USHRT(FUNCNAME_TRIANGULATIONORDER3BOUNDARYEDGECOUNTEULER(C_PUSHRT3(a,b,c)))
#define triangulation_order3_boundary_node(a,b,c) FUNCNAME_TRIANGULATIONORDER3BOUNDARYNODE(C_2DTPI(a,b,c))
#define triangulation_order3_check(a,b,c) R_UCHR(FUNCNAME_TRIANGULATIONORDER3CHECK(C_2DTPI(a,b,c)))
#define triangulation_order3_edge_check(a,b) R_SHRT(FUNCNAME_TRIANGULATIONORDER3EDGECHECK(C_DTPI(a,b)))
#define triangulation_order3_neighbor(a,b,c,d,e,f) FUNCNAME_TRIANGULATIONORDER3NEIGHBOR(C_DTPI2DTPI(a,b,c,d,e,f))
#define triangulation_order3_refine_compute(a,b,c,d,e,f,g,h,i) FUNCNAME_TRIANGULATIONORDER3REFINECOMPUTE(C_2DTPITPI2DTPIPITPI(a,b,c,d,e,f,g,h,i))
#define triangulation_order3_refine_size(a,b,c,d,e,f) FUNCNAME_TRIANGULATIONORDER3REFINESIZE(C_2DT4PI(a,b,c,d,e,f))
#define triangulation_order6_adj_count(a,b,c,d,e) R_USHRT(FUNCNAME_TRIANGULATIONORDER6ADJCOUNT(C_2DT3PI(a,b,c,d,e)))
#define triangulation_order6_adj_set(a,b,c,d,e,f) FUNCNAME_TRIANGULATIONORDER6ADJSET(C_2DT2PIDTPI(a,b,c,d,e,f))
#define triangulation_order6_boundary_edge_count(a,b) R_USHRT(FUNCNAME_TRIANGULATIONORDER6BOUNDARYEDGECOUNT(C_DTPI(a,b)))
#define triangulation_order6_boundary_edge_count_euler(a,b,c) R_USHRT(FUNCNAME_TRIANGULATIONORDER6BOUNDARYEDGECOUNTEULER(C_PUSHRT3(a,b,c)))
#define triangulation_order6_boundary_node(a,b,c) FUNCNAME_TRIANGULATIONORDER6BOUNDARYNODE(C_2DTPI(a,b,c))
#define triangulation_order6_refine_compute(a,b,c,d,e,f,g,h,i) FUNCNAME_TRIANGULATIONORDER6REFINECOMPUTE(C_2DTPITPI2DTPIPITPI(a,b,c,d,e,f,g,h,i))
#define triangulation_order6_refine_size(a,b,c,d,e,f) FUNCNAME_TRIANGULATIONORDER6REFINESIZE(C_2DT4PI(a,b,c,d,e,f))
#define triangulation_order6_to_order3(a,b) FUNCNAME_TRIANGULATIONORDER6TOORDER3(C_DTPI(a,b))
#define triangulation_order6_vertex_count(a,b) R_USHRT(FUNCNAME_TRIANGULATIONORDER6VERTEXCOUNT(C_DTPI(a,b)))
#define triangulation_search_naive(a,b,c,d,e,f) R_SHRT(FUNCNAME_TRIANGULATIONSEARCHNAIVE(C_DTPIT2DTPIPIT(a,b,c,d,e,f)))
#define voronoi_polygon_area(a,b,c,d,e) R_DBL(FUNCNAME_VORONOIPOLYGONAREA(C_3DTPIPIT(a,b,d,c,e)))
#define voronoi_polygon_centroid(a,b,c,d,e) FUNCNAME_VORONOIPOLYGONCENTROID(C_3DTPIPIT(a,b,d,c,e))
#define voronoi_polygon_vertices(a,b,c,d,e,f) FUNCNAME_VORONOIPOLYGONVERTICES(C_3DTPIPIT(a,b,d,c,e))
#define triangulation_neighbor_triangles(a,b,c) FUNCNAME_TRIANGULATIONNEIGHBORTRIANGLES(C_2DTPI(a,b,c))
#define triangulation_search_delaunay(a,b,c,d,e,f,g,h,i,j,k,l,m) FUNCNAME_TRIANGULATIONSEARCHDELAUNAY(C_DTPIT2DT2PIPITPI3PIT2PI(a,b,c,d,e,f,g,h,i,j,k,l,m))

__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEORDER3REFERENCETOPHYSICAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEORDER3PHYSICALTOREFERENCE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_ALPHAMEASURE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_AREAMEASURE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_BANDWIDTH(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DELAUNAYSWAPTEST(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NSADJCOLSET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NSADJCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NSADJINSERT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_NSADJROWSET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_QMEASURE(void *);  
__MATHSUITE __JBURKARDT void * FUNCNAME_QUADCONVEXRANDOM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONAREA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONAREAS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONDELAUNAYDISCREPANCYCOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3ADJCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3ADJSET2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3BOUNDARYEDGECOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3BOUNDARYEDGECOUNTEULER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3CHECK(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3EDGECHECK(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3NEIGHBOR(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3REFINECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6ADJCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6BOUNDARYEDGECOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6REFINECOMPUTE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3REFINESIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6REFINESIZE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6VERTEXCOUNT(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_VORONOIPOLYGONAREA(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONSEARCHDELAUNAY(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_POINTSDELAUNAYNAIVE2D(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONNEIGHBORELEMENTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONNODEORDER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3ADJSET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3ADJACENCY(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER3BOUNDARYNODE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6ADJSET(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6BOUNDARYNODE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6TOORDER3(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_VORONOIPOLYGONCENTROID(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_VORONOIPOLYGONVERTICES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONNEIGHBORTRIANGLES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONORDER6BOUNDARYEDGECOUNTEULER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGULATIONSEARCHNAIVE(void *);

#endif
