#ifndef WRAPPER_TRIANGLE_NCO_RULE_H_INCLUDED
#define WRAPPER_TRIANGLE_NCO_RULE_H_INCLUDED

#define triangle_nco_degree(a) R_USHRT(FUNCNAME_TRIANGLENCODEGREE(C_SUSHRT(a)))
#define triangle_nco_order_num(a) R_USHRT(FUNCNAME_TRIANGLENCOORDERNUM(C_SUSHRT(a)))
#define triangle_nco_rule(a,b,c,d) FUNCNAME_TRIANGLENCORULE(C_2DT2PIT(a,b,c,d))
#define triangle_nco_rule_num() R_USHRT(FUNCNAME_TRIANGLENCORULENUM(NULL))
#define triangle_nco_suborder(a,b) FUNCNAME_TRIANGLENCOSUBORDER(C_PUSHRT2(a,b))
#define triangle_nco_suborder_num(a) R_USHRT(FUNCNAME_TRIANGLENCOSUBORDERNUM(C_SUSHRT(a)))
#define triangle_nco_subrule(a,b,c,d) FUNCNAME_TRIANGLENCOSUBRULE(C_2DT2PIT(a,b,c,d))
#define triangle_nco_subrule_01(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE01(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_02(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE02(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_03(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE03(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_04(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE04(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_05(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE05(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_06(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE06(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_07(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE07(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_08(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE08(C_DT4PI(a,b,c,d,e))
#define triangle_nco_subrule_09(a,b,c,d,e) FUNCNAME_TRIANGLENCOSUBRULE09(C_DT4PI(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCORULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE02(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE04(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE05(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE08(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBRULE09(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBORDER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCORULENUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCODEGREE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOORDERNUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCOSUBORDERNUM(void *);

#endif
