#ifndef WRAPPER_TRIANGULATION_SVG_H_INCLUDED
#define WRAPPER_TRIANGULATION_SVG_H_INCLUDED

#define mesh_base_zero(a,b,c,d) FUNCNAME_MESHBASEZERO(C_3DTPI(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_MESHBASEZERO(void *);

#endif
