#ifndef WRAPPER_TRIANGULATION_NODE_TO_ELEMENT_H_INCLUDED
#define WRAPPER_TRIANGULATION_NODE_TO_ELEMENT_H_INCLUDED

#define mesh_base_one(a,b,c,d) FUNCNAME_MESHBASEONE(C_3DTPI(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_MESHBASEONE(void *);

#endif
