#ifndef WRAPPER_TRIANGLE_FEKETE_RULE_H_INCLUDED
#define WRAPPER_TRIANGLE_FEKETE_RULE_H_INCLUDED

#define fekete_degree(a) R_USHRT(FUNCNAME_FEKETEDEGREE(C_SUSHRT(a)))
#define fekete_order_num(a) R_USHRT(FUNCNAME_FEKETEORDERNUM(C_SUSHRT(a)))
#define fekete_rule(a,b,c,d) FUNCNAME_FEKETERULE(C_2DT2PIT(a,b,c,d))
#define fekete_rule_num() R_USHRT(FUNCNAME_FEKETERULENUM(NULL))
#define fekete_suborder(a,b) FUNCNAME_FEKETESUBORDER(C_PUSHRT2(a,b))
#define fekete_suborder_num(a) R_USHRT(FUNCNAME_FEKETESUBORDERNUM(C_SUSHRT(a)))
#define fekete_subrule(a,b,c,d) FUNCNAME_FEKETESUBRULE(C_2DT2PIT(a,b,c,d))
#define fekete_subrule_1(a,b,c) FUNCNAME_FEKETESUBRULE1(C_DT2PIT(a,b,c))
#define fekete_subrule_2(a,b,c) FUNCNAME_FEKETESUBRULE2(C_DT2PIT(a,b,c))
#define fekete_subrule_3(a,b,c) FUNCNAME_FEKETESUBRULE3(C_DT2PIT(a,b,c))
#define fekete_subrule_4(a,b,c) FUNCNAME_FEKETESUBRULE4(C_DT2PIT(a,b,c))
#define fekete_subrule_5(a,b,c) FUNCNAME_FEKETESUBRULE5(C_DT2PIT(a,b,c))
#define fekete_subrule_6(a,b,c) FUNCNAME_FEKETESUBRULE6(C_DT2PIT(a,b,c))
#define fekete_subrule_7(a,b,c) FUNCNAME_FEKETESUBRULE7(C_DT2PIT(a,b,c))
#define reference_to_physical_t3(a,b,c,d) FUNCNAME_REFERENCETOPHYSICALT3(C_DT3PIT(b,c,d,a))

__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETERULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE1(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE2(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE3(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE4(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE5(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE6(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBRULE7(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_REFERENCETOPHYSICALT3(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBORDER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETERULENUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETEDEGREE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETEORDERNUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_FEKETESUBORDERNUM(void *);

#endif
