#ifndef WRAPPER_TRIANGLE_FELIPPA_RULE_H_INCLUDED
#define WRAPPER_TRIANGLE_FELIPPA_RULE_H_INCLUDED

#define triangle_unit_o01(a,b) FUNCNAME_TRIANGLEUNITO01(C_PPDBL2(a,b))
#define triangle_unit_o03(a,b) FUNCNAME_TRIANGLEUNITO03(C_PPDBL2(a,b))
#define triangle_unit_o03b(a,b) FUNCNAME_TRIANGLEUNITO03B(C_PPDBL2(a,b))
#define triangle_unit_o06(a,b) FUNCNAME_TRIANGLEUNITO06(C_PPDBL2(a,b))
#define triangle_unit_o06b(a,b) FUNCNAME_TRIANGLEUNITO06B(C_PPDBL2(a,b))
#define triangle_unit_o07(a,b) FUNCNAME_TRIANGLEUNITO07(C_PPDBL2(a,b))
#define triangle_unit_o12(a,b) FUNCNAME_TRIANGLEUNITO12(C_PPDBL2(a,b))
#define triangle_unit_volume() R_DBL(FUNCNAME_TRIANGLEUNITVOLUME(NULL))

__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITO01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITO03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITO03B(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITO06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITO06B(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITO07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITO12(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLEUNITVOLUME(void *);

#endif
