#ifndef WRAPPER_TRIANGLE_NCC_RULE_H_INCLUDED
#define WRAPPER_TRIANGLE_NCC_RULE_H_INCLUDED

#define triangle_ncc_degree(a) R_USHRT(FUNCNAME_TRIANGLENCCDEGREE(C_SUSHRT(a)))
#define triangle_ncc_order_num(a) R_USHRT(FUNCNAME_TRIANGLENCCORDERNUM(C_SUSHRT(a)))
#define triangle_ncc_rule(a,b,c,d) FUNCNAME_TRIANGLENCCRULE(C_2DT2PIT(a,b,c,d))
#define triangle_ncc_rule_num() R_USHRT(FUNCNAME_TRIANGLENCCRULENUM(NULL))
#define triangle_ncc_suborder(a,b) FUNCNAME_TRIANGLENCCSUBORDER(C_PUSHRT2(a,b))
#define triangle_ncc_suborder_num(a) R_USHRT(FUNCNAME_TRIANGLENCCSUBORDERNUM(C_SUSHRT(a)))
#define triangle_ncc_subrule(a,b,c,d) FUNCNAME_TRIANGLENCCSUBRULE(C_2DT2PIT(a,b,c,d))
#define triangle_ncc_subrule_01(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE01(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_02(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE02(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_03(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE03(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_04(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE04(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_05(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE05(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_06(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE06(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_07(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE07(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_08(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE08(C_DT4PI(a,b,c,d,e))
#define triangle_ncc_subrule_09(a,b,c,d,e) FUNCNAME_TRIANGLENCCSUBRULE09(C_DT4PI(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCRULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE01(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE02(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE03(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE04(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE05(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE06(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE07(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE08(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBRULE09(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBORDER(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCRULENUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCDEGREE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCORDERNUM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRIANGLENCCSUBORDERNUM(void *);

#endif
