#ifndef WRAPPER_TRUNCATED_NORMAL_H_INCLUDED
#define WRAPPER_TRUNCATED_NORMAL_H_INCLUDED

#define truncated_normal_ab_cdf_values(a,b,c,d,e,f,g) FUNCNAME_TRUNCATEDNORMALABCDFVALUES(C_PDT6PIT(a,b,c,d,e,f,g))
#define truncated_normal_ab_pdf_values(a,b,c,d,e,f,g) FUNCNAME_TRUNCATEDNORMALABPDFVALUES(C_PDT6PIT(a,b,c,d,e,f,g))
#define truncated_normal_a_cdf_values(a,b,c,d,e,f) FUNCNAME_TRUNCATEDNORMALACDFVALUES(C_4PITPDTPIT(b,c,d,e,a,f))
#define truncated_normal_a_pdf_values(a,b,c,d,e,f) FUNCNAME_TRUNCATEDNORMALAPDFVALUES(C_4PITPDTPIT(b,c,d,e,a,f))
#define truncated_normal_b_cdf_values(a,b,c,d,e,f) FUNCNAME_TRUNCATEDNORMALBCDFVALUES(C_4PITPDTPIT(b,c,d,e,a,f))
#define truncated_normal_b_pdf_values(a,b,c,d,e,f) FUNCNAME_TRUNCATEDNORMALBPDFVALUES(C_4PITPDTPIT(b,c,d,e,a,f))

__MATHSUITE __JBURKARDT void * FUNCNAME_TRUNCATEDNORMALABCDFVALUES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRUNCATEDNORMALABPDFVALUES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRUNCATEDNORMALACDFVALUES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRUNCATEDNORMALAPDFVALUES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRUNCATEDNORMALBCDFVALUES(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_TRUNCATEDNORMALBPDFVALUES(void *);

#endif
