#ifndef WRAPPER_VANDERMONDE_APPROX_2D_H_INCLUDED
#define WRAPPER_VANDERMONDE_APPROX_2D_H_INCLUDED

#define vandermonde_approx_2d_coef(a,b,c,d,e) FUNCNAME_VANDERMONDEAPPROX2DCOEF(C_2DT3PIT(a,b,c,d,e))
#define vandermonde_approx_2d_matrix(a,b,c,d,e) FUNCNAME_VANDERMONDEAPPROX2DMATRIX(C_3DT2PIT(a,b,c,d,e))

__MATHSUITE __JBURKARDT void * FUNCNAME_VANDERMONDEAPPROX2DCOEF(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_VANDERMONDEAPPROX2DMATRIX(void *);

#endif
