#ifndef WRAPPER_VANDERMONDE_INTERP_2D_H_INCLUDED
#define WRAPPER_VANDERMONDE_INTERP_2D_H_INCLUDED

#define vandermonde_interp_2d_matrix(a,b,c,d) FUNCNAME_VANDERMONDEINTERP2DMATRIX(C_2DT2PIT(a,b,c,d))

__MATHSUITE __JBURKARDT void * FUNCNAME_VANDERMONDEINTERP2DMATRIX(void *);

#endif
