#ifndef WRAPPER_WAVELET_H_INCLUDED
#define WRAPPER_WAVELET_H_INCLUDED

#define r8vec_convolution(a,b,c,d) FUNCNAME_R8VECCONVOLUTION(C_2DT2PIT(a,c,b,d))
#define cascade(a,b,c,d,e) FUNCNAME_CASCADE(C_3DT2PIT(a,b,d,c,e))
#define daub_coefficients(a) FUNCNAME_DAUBCOEFFICIENTS(C_SUSHRT(a))
#define daub2_matrix(a) FUNCNAME_DAUB2MATRIX(C_SUSHRT(a))
#define daub2_scale(a,b) R_DBL(FUNCNAME_DAUB2SCALE(C_SIT(a,b)))
#define daub2_transform(a,b) FUNCNAME_DAUB2TRANSFORM(C_DTPIT(a,b))
#define daub2_transform_inverse(a,b) FUNCNAME_DAUB2TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub4_matrix(a) FUNCNAME_DAUB4MATRIX(C_SUSHRT(a))
#define daub4_scale(a,b) R_DBL(FUNCNAME_DAUB4SCALE(C_SIT(a,b)))
#define daub4_transform(a,b) FUNCNAME_DAUB4TRANSFORM(C_DTPIT(a,b))
#define daub4_transform_inverse(a,b) FUNCNAME_DAUB4TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub6_matrix(a) FUNCNAME_DAUB6MATRIX(C_SUSHRT(a))
#define daub6_scale(a,b) R_DBL(FUNCNAME_DAUB6SCALE(C_SIT(a,b)))
#define daub6_transform(a,b) FUNCNAME_DAUB6TRANSFORM(C_DTPIT(a,b))
#define daub6_transform_inverse(a,b) FUNCNAME_DAUB6TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub8_matrix(a) FUNCNAME_DAUB8MATRIX(C_SUSHRT(a))
#define daub8_scale(a,b) R_DBL(FUNCNAME_DAUB8SCALE(C_SIT(a,b)))
#define daub8_transform(a,b) FUNCNAME_DAUB8TRANSFORM(C_DTPIT(a,b))
#define daub8_transform_inverse(a,b) FUNCNAME_DAUB8TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub10_matrix(a) FUNCNAME_DAUB10MATRIX(C_SUSHRT(a))
#define daub10_scale(a,b) R_DBL(FUNCNAME_DAUB10SCALE(C_SIT(a,b)))
#define daub10_transform(a,b) FUNCNAME_DAUB10TRANSFORM(C_DTPIT(a,b))
#define daub10_transform_inverse(a,b) FUNCNAME_DAUB10TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub12_matrix(a) FUNCNAME_DAUB12MATRIX(C_SUSHRT(a))
#define daub12_transform(a,b) FUNCNAME_DAUB12TRANSFORM(C_DTPIT(a,b))
#define daub12_transform_inverse(a,b) FUNCNAME_DAUB12TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub14_transform(a,b) FUNCNAME_DAUB14TRANSFORM(C_DTPIT(a,b))
#define daub14_transform_inverse(a,b) FUNCNAME_DAUB14TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub16_transform(a,b) FUNCNAME_DAUB16TRANSFORM(C_DTPIT(a,b))
#define daub16_transform_inverse(a,b) FUNCNAME_DAUB16TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub18_transform(a,b) FUNCNAME_DAUB18TRANSFORM(C_DTPIT(a,b))
#define daub18_transform_inverse(a,b) FUNCNAME_DAUB18TRANSFORMINVERSE(C_DTPIT(a,b))
#define daub20_transform(a,b) FUNCNAME_DAUB20TRANSFORM(C_DTPIT(a,b))
#define daub20_transform_inverse(a,b) FUNCNAME_DAUB20TRANSFORMINVERSE(C_DTPIT(a,b))

__MATHSUITE __JBURKARDT void * FUNCNAME_R8VECCONVOLUTION(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_CASCADE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUBCOEFFICIENTS(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB2MATRIX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB2TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB2TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB4MATRIX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB4TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB4TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB6MATRIX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB6TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB6TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB8MATRIX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB8TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB8TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB10MATRIX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB10TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB10TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB12MATRIX(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB12TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB12TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB14TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB14TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB16TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB16TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB18TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB18TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB20TRANSFORM(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB20TRANSFORMINVERSE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB2SCALE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB4SCALE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB6SCALE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB8SCALE(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_DAUB10SCALE(void *);

#endif
