#ifndef WRAPPER_WEDGE_EXACTNESS_H_INCLUDED
#define WRAPPER_WEDGE_EXACTNESS_H_INCLUDED

#define wedge01_integral(a) R_DBL(FUNCNAME_WEDGE01INTEGRAL(a))
#define wedge01_volume() R_DBL(FUNCNAME_WEDGE01VOLUME(NULL))

__MATHSUITE __JBURKARDT void * FUNCNAME_WEDGE01INTEGRAL(void *);
__MATHSUITE __JBURKARDT void * FUNCNAME_WEDGE01VOLUME(void *);

#endif
