/*
    File: exprinit.c
    Auth: Brian Allen Vanderburg II
    Date: Thursday, May 1, 2003
    Desc: Extra functions and routines for ExprEval

    This file is part of ExprEval.
*/

/* Include files */
#include "exprincl.h"

#include "exprpriv.h"
#include "..\defaults.h"


/* Macro for adding a function node type */
#define EXPR_ADDFUNC_TYPE(name, type, argmin, argmax, refmin, refmax) \
err = exprFuncListAddType(flist, name, type, argmin, argmax, refmin, refmax); \
if(err != EXPR_ERROR_NOERROR) \
    return err;

/* Macro for adding a constant */
#define EXPR_ADDCONST(name, val) \
err = exprValListAdd(vlist, name, val); \
if(err != EXPR_ERROR_NOERROR) \
    return err;

/* Call this function to initialize these functions into a function list */
int exprFuncListInit(exprFuncList *flist)
    {
    int err;

    if(flist == NULL)
        return EXPR_ERROR_NULLPOINTER;

    EXPR_ADDFUNC_TYPE(EXIT_CMD, EXPR_NODEFUNC_EXIT, 1, 1, 0, 0); // safe-exit the program
    EXPR_ADDFUNC_TYPE(MHSS_CMD, EXPR_NODEFUNC_MHSS, 0, 0, 0, 0);
    EXPR_ADDFUNC_TYPE("abs", EXPR_NODEFUNC_ABS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("mod", EXPR_NODEFUNC_MOD, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("ipart", EXPR_NODEFUNC_IPART, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("fpart", EXPR_NODEFUNC_FPART, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("min", EXPR_NODEFUNC_MIN, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE("max", EXPR_NODEFUNC_MAX, 1, -1, 0, 0);

    // MACRO MODIFICATE CON GLI IDENTIFIER DI DEFAULT
    // DEL MIO PROGRAMMA

    EXPR_ADDFUNC_TYPE(IDENTIFIER_BITCOUNTER, EXPR_NODEFUNC_BITCOUNTER, 2, 2, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_VERSION, EXPR_NODEFUNC_VERSION, 0, 0, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_PREC, EXPR_NODEFUNC_PREC, 0, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_STABFACT, EXPR_NODEFUNC_STABFACT, 0, 1, 0, 0);
    
	EXPR_ADDFUNC_TYPE(IDENTIFIER_MINSRNUMBER, EXPR_NODEFUNC_MINSRNUMBER, 0, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ALGEBRA, EXPR_NODEFUNC_ALGEBRA, 0, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_RSEED, EXPR_NODEFUNC_RSEED, 0, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MMIFIBO, EXPR_NODEFUNC_MMIFIBO, 0, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MMIFACT, EXPR_NODEFUNC_MMIFACT, 0, 1, 0, 0);
   	EXPR_ADDFUNC_TYPE(IDENTIFIER_MMIEVENSFACT, EXPR_NODEFUNC_MMIEVENSFACT, 0, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MMIODDSFACT, EXPR_NODEFUNC_MMIODDSFACT, 0, 1, 0, 0);

	

    //
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ADDIZIONEBINARIA, EXPR_NODEFUNC_BINSUM, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOTTRAZIONEBINARIA, EXPR_NODEFUNC_BINSUB, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COMPLEMENT, EXPR_NODEFUNC_COMP, 2, 2, 0, 0);
    //
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ELEVAMENTOAPOTENZA, EXPR_NODEFUNC_POW, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_RADICEQUADRATA, EXPR_NODEFUNC_SQRT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_RADICECUBICA, EXPR_NODEFUNC_CBRT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_RADICENESIMA, EXPR_NODEFUNC_ROOT, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SINANDSINH, EXPR_NODEFUNC_SIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SINANDSINH"h", EXPR_NODEFUNC_SINH, 1, 1, 0, 0);
    //
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CSCANDCSCH, EXPR_NODEFUNC_CSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CSCANDCSCH"h", EXPR_NODEFUNC_CSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ASINANDASINH, EXPR_NODEFUNC_ASIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ASINANDASINH"h", EXPR_NODEFUNC_ASINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ACSCANDACSCH, EXPR_NODEFUNC_ACSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ACSCANDACSCH"h", EXPR_NODEFUNC_ACSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COSANDCOSH, EXPR_NODEFUNC_COS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COSANDCOSH"h", EXPR_NODEFUNC_COSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SECANDSECH, EXPR_NODEFUNC_SEC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SECANDSECH"h", EXPR_NODEFUNC_SECH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ACOSANDACOSH, EXPR_NODEFUNC_ACOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ACOSANDACOSH"h", EXPR_NODEFUNC_ACOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ASECANDASECH, EXPR_NODEFUNC_ASEC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ASECANDASECH"h", EXPR_NODEFUNC_ASECH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_TANANDTANH, EXPR_NODEFUNC_TAN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_TANANDTANH"h", EXPR_NODEFUNC_TANH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COTANDCOTH, EXPR_NODEFUNC_COT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COTANDCOTH"h", EXPR_NODEFUNC_COTH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ATANANDATANH, EXPR_NODEFUNC_ATAN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ATANANDATANH"h", EXPR_NODEFUNC_ATANH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ACOTANDACOTH, EXPR_NODEFUNC_ACOT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ACOTANDACOTH"h", EXPR_NODEFUNC_ACOTH, 1, 1, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSINANDHSINH, EXPR_NODEFUNC_HSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSINANDHSINH"h", EXPR_NODEFUNC_HSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSINANDQSINH, EXPR_NODEFUNC_QSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSINANDQSINH"h", EXPR_NODEFUNC_QSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOSANDHCOSH, EXPR_NODEFUNC_HCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOSANDHCOSH"h", EXPR_NODEFUNC_HCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOSANDQCOSH, EXPR_NODEFUNC_QCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOSANDQCOSH"h", EXPR_NODEFUNC_QCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSECANDHSECH, EXPR_NODEFUNC_HSEC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSECANDHSECH"h", EXPR_NODEFUNC_HSECH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSECANDQSECH, EXPR_NODEFUNC_QSEC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSECANDQSECH"h", EXPR_NODEFUNC_QSECH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCSCANDHCSCH, EXPR_NODEFUNC_HCSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCSCANDHCSCH"h", EXPR_NODEFUNC_HCSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCSCANDQCSCH, EXPR_NODEFUNC_QCSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCSCANDQCSCH"h", EXPR_NODEFUNC_QCSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HTANANDHTANH, EXPR_NODEFUNC_HTAN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HTANANDHTANH"h", EXPR_NODEFUNC_HTANH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QTANANDQTANH, EXPR_NODEFUNC_QTAN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QTANANDQTANH"h", EXPR_NODEFUNC_QTANH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOTANDHCOTH, EXPR_NODEFUNC_HCOT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOTANDHCOTH"h", EXPR_NODEFUNC_HCOTH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOTANDQCOTH, EXPR_NODEFUNC_QCOT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOTANDQCOTH"h", EXPR_NODEFUNC_QCOTH, 1, 1, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_VSINANDVSINH, EXPR_NODEFUNC_VSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_VSINANDVSINH"h", EXPR_NODEFUNC_VSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CVSINANDCVSINH, EXPR_NODEFUNC_CVSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CVSINANDCVSINH"h", EXPR_NODEFUNC_CVSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_VCOSANDVCOSH, EXPR_NODEFUNC_VCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_VCOSANDVCOSH"h", EXPR_NODEFUNC_VCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CVCOSANDCVCOSH, EXPR_NODEFUNC_CVCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CVCOSANDCVCOSH"h", EXPR_NODEFUNC_CVCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HVSINANDHVSINH, EXPR_NODEFUNC_HVSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HVSINANDHVSINH"h", EXPR_NODEFUNC_HVSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCVSINANDHCVSINH, EXPR_NODEFUNC_HCVSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCVSINANDHCVSINH"h", EXPR_NODEFUNC_HCVSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QVSINANDQVSINH, EXPR_NODEFUNC_QVSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QVSINANDQVSINH"h", EXPR_NODEFUNC_QVSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCVSINANDQCVSINH, EXPR_NODEFUNC_HHCVSIN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCVSINANDQCVSINH"h", EXPR_NODEFUNC_HHCVSINH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HVCOSANDHVCOSH, EXPR_NODEFUNC_HVCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HVCOSANDHVCOSH"h", EXPR_NODEFUNC_HVCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCVCOSANDHCVCOSH, EXPR_NODEFUNC_HCVCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCVCOSANDHCVCOSH"h", EXPR_NODEFUNC_HCVCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QVCOSANDQVCOSH, EXPR_NODEFUNC_QVCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QVCOSANDQVCOSH"h", EXPR_NODEFUNC_QVCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCVCOSANDQCVCOSH, EXPR_NODEFUNC_QCVCOS, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCVCOSANDQCVCOSH"h", EXPR_NODEFUNC_QCVCOSH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ESECANDESECH, EXPR_NODEFUNC_ESEC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ESECANDESECH"h", EXPR_NODEFUNC_ESECH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ECSCANDECSCH, EXPR_NODEFUNC_ECSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ECSCANDECSCH"h", EXPR_NODEFUNC_ECSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HESECANDHESECH, EXPR_NODEFUNC_HESEC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HESECANDHESECH"h", EXPR_NODEFUNC_HESECH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HECSCANDHECSCH, EXPR_NODEFUNC_HECSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HECSCANDHECSCH"h", EXPR_NODEFUNC_HECSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QESECANDQESECH, EXPR_NODEFUNC_QESEC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QESECANDQESECH"h", EXPR_NODEFUNC_QESECH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QECSCANDQECSCH, EXPR_NODEFUNC_QECSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QECSCANDQECSCH"h", EXPR_NODEFUNC_QECSCH, 1, 1, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_SINCANDSINCH, EXPR_NODEFUNC_SINC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SINCANDSINCH"h", EXPR_NODEFUNC_SINCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSINCANDHSINCH, EXPR_NODEFUNC_HSINC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSINCANDHSINCH"h", EXPR_NODEFUNC_HSINCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSINCANDQSINCH, EXPR_NODEFUNC_QSINC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSINCANDQSINCH"h", EXPR_NODEFUNC_QSINCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COSCANDCOSCH, EXPR_NODEFUNC_COSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COSCANDCOSCH"h", EXPR_NODEFUNC_COSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOSCANDHCOSCH, EXPR_NODEFUNC_HCOSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOSCANDHCOSCH"h", EXPR_NODEFUNC_HCOSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOSCANDQCOSCH, EXPR_NODEFUNC_QCOSC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOSCANDQCOSCH"h", EXPR_NODEFUNC_QCOSCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SECCANDSECCH, EXPR_NODEFUNC_SECC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SECCANDSECCH"h", EXPR_NODEFUNC_SECCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSECCANDHSECCH, EXPR_NODEFUNC_HSECC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HSECCANDHSECCH"h", EXPR_NODEFUNC_HSECCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSECCANDQSECCH, EXPR_NODEFUNC_QSECC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QSECCANDQSECCH"h", EXPR_NODEFUNC_QSECCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CSCCANDCSCCH, EXPR_NODEFUNC_CSCC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CSCCANDCSCCH"h", EXPR_NODEFUNC_CSCCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCSCCANDHCSCCH, EXPR_NODEFUNC_HCSCC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCSCCANDHCSCCH"h", EXPR_NODEFUNC_HCSCCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCSCCANDQCSCCH, EXPR_NODEFUNC_QCSCC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCSCCANDQCSCCH"h", EXPR_NODEFUNC_QCSCCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_TANCANDTANCH, EXPR_NODEFUNC_TANC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_TANCANDTANCH"h", EXPR_NODEFUNC_TANCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HTANCANDHTANCH, EXPR_NODEFUNC_HTANC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HTANCANDHTANCH"h", EXPR_NODEFUNC_HTANCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QTANCANDQTANCH, EXPR_NODEFUNC_QTANC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QTANCANDQTANCH"h", EXPR_NODEFUNC_QTANCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COTCANDCOTCH, EXPR_NODEFUNC_COTC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COTCANDCOTCH"h", EXPR_NODEFUNC_COTCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOTCANDHCOTCH, EXPR_NODEFUNC_HCOTC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_HCOTCANDHCOTCH"h", EXPR_NODEFUNC_HCOTCH, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOTCANDQCOTCH, EXPR_NODEFUNC_QCOTC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_QCOTCANDQCOTCH"h", EXPR_NODEFUNC_QCOTCH, 1, 1, 0, 0);

    //
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ATAN2, EXPR_NODEFUNC_ATAN2, 2, 2, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_MATRIXDET, EXPR_NODEFUNC_MATRIXDET, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MATRIXNORM, EXPR_NODEFUNC_MATRIXNORM, 2, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MATRIXTRACE, EXPR_NODEFUNC_MATRIXTRACE, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MATRIXRANK, EXPR_NODEFUNC_MATRIXRANK, 2, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MATRIXILLCHK, EXPR_NODEFUNC_MATRIXILLCHK, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SCALARPROD, EXPR_NODEFUNC_SCALARPROD, 1, -1, 0, 0);


    EXPR_ADDFUNC_TYPE(IDENTIFIER_LOGARITMO, EXPR_NODEFUNC_LOG, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_LOGARITMO2, EXPR_NODEFUNC_LOG2, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("pow10", EXPR_NODEFUNC_POW10, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("ln", EXPR_NODEFUNC_LN, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_EXPANDEXPC, EXPR_NODEFUNC_EXP, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_EXPANDEXPC"c", EXPR_NODEFUNC_EXPC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_EXP10ANDEXP10C, EXPR_NODEFUNC_EXP10, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_EXP10ANDEXP10C"c", EXPR_NODEFUNC_EXP10C, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_EXP2ANDEXP2C, EXPR_NODEFUNC_EXP2, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_EXP2ANDEXP2C"c", EXPR_NODEFUNC_EXP2C, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_LOGARITMOBN, EXPR_NODEFUNC_LOGN, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_LOGARITMOC, EXPR_NODEFUNC_LOGC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("lnc", EXPR_NODEFUNC_LNC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_LOGARITMO2C, EXPR_NODEFUNC_LOG2C, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_LOGARITMO1P, EXPR_NODEFUNC_LOG1P, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_LOGARITMO1PC, EXPR_NODEFUNC_LOG1PC, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("ceil", EXPR_NODEFUNC_CEIL, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("floor", EXPR_NODEFUNC_FLOOR, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_RISOLUTOREEQUAZIONISECONDOGRADO, EXPR_NODEFUNC_SGEQSOLVER, 3, 3, 2, 2);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COMPLEXSUM, EXPR_NODEFUNC_COMPLEXSUM, 4, 4, 2, 2);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COMPLEXPROD, EXPR_NODEFUNC_COMPLEXPROD, 4, 4, 2, 2);
    EXPR_ADDFUNC_TYPE("rand", EXPR_NODEFUNC_RAND, 0, 0, 1, 1);
    EXPR_ADDFUNC_TYPE("random", EXPR_NODEFUNC_RANDOM, 2, 2, 1, 1);
    EXPR_ADDFUNC_TYPE("randomize", EXPR_NODEFUNC_RANDOMIZE, 0, 0, 1, 1);
    EXPR_ADDFUNC_TYPE("deg", EXPR_NODEFUNC_DEG, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("rad", EXPR_NODEFUNC_RAD, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE("recttopolr", EXPR_NODEFUNC_RECTTOPOLR, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("recttopola", EXPR_NODEFUNC_RECTTOPOLA, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("poltorectx", EXPR_NODEFUNC_POLTORECTX, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("poltorecty", EXPR_NODEFUNC_POLTORECTY, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CAMBIAMENTODIBASE, EXPR_NODEFUNC_CBASE, 3, 3, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_NESIMONUMEROPRIMO, EXPR_NODEFUNC_NPNUM, 1, 1, 0, 0);
    //
    EXPR_ADDFUNC_TYPE(IDENTIFIER_PRIMORIALE, EXPR_NODEFUNC_PRIMORIAL, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMAPRIMINNUMERIPRIMI, EXPR_NODEFUNC_FPNSUM, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_FIBONACCIALE, EXPR_NODEFUNC_FIBONACCIAL, 1, 1, 0, 0);
    //

    EXPR_ADDFUNC_TYPE(IDENTIFIER_ALIAS_MCM, EXPR_NODEFUNC_LCM, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_ALIAS_MCD, EXPR_NODEFUNC_GCD, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_FATTORIALE, EXPR_NODEFUNC_FACT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SEMIFATTORIALE, EXPR_NODEFUNC_SFACT, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_STIRLING, EXPR_NODEFUNC_STIRLING, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_FIBONACCI, EXPR_NODEFUNC_FIBO, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_PERMUTATION, EXPR_NODEFUNC_PERM, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_COMBINATION, EXPR_NODEFUNC_COMB, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMASUCCESSIONEGEOMETRICA, EXPR_NODEFUNC_GSUM, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMASUCCESSIONEARMONICA, EXPR_NODEFUNC_ASUM, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMASUCCESSIONEARMONICAGEN, EXPR_NODEFUNC_GASUM, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMASUCCESSIONEFIBONACCI, EXPR_NODEFUNC_FSUM, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMASUCCESSIONEFATTORIALE, EXPR_NODEFUNC_FASUM, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMASUCCESSIONESEMIFATTORIALE, EXPR_NODEFUNC_SFASUM, 1, 1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMAPRIMINNUMERI, EXPR_NODEFUNC_FNNSUM, 1, 1, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_SOMMATORIA, EXPR_NODEFUNC_SUM, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_PRODUTTORIA, EXPR_NODEFUNC_PRODUCT, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MEDIA, EXPR_NODEFUNC_MEDIA, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MEDIAGEOMETRICA, EXPR_NODEFUNC_GEOMEDIA, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MEDIAARMONICA, EXPR_NODEFUNC_ARMEDIA, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MEDIAPOTENZA, EXPR_NODEFUNC_POWMEDIA, 2, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_VALORECENTRALE, EXPR_NODEFUNC_CVAL, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_MEDIANA, EXPR_NODEFUNC_MEDIANA, 1, -1, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_CELSIUSFAHRENHEIT, EXPR_NODEFUNC_CELSIUSFAHRENHEIT, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CELSIUSKELVIN, EXPR_NODEFUNC_CELSIUSKELVIN, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CELSIUSRANKINE, EXPR_NODEFUNC_CELSIUSRANKINE, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CELSIUSREAUMUR, EXPR_NODEFUNC_CELSIUSREAUMUR, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CELSIUSNEWTON, EXPR_NODEFUNC_CELSIUSNEWTON, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CELSIUSDELISLE, EXPR_NODEFUNC_CELSIUSDELISLE, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_CELSIUSROMER, EXPR_NODEFUNC_CELSIUSROMER, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_FAHRENHEITKELVIN, EXPR_NODEFUNC_FAHRENHEITKELVIN, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_FAHRENHEITRANKINE, EXPR_NODEFUNC_FAHRENHEITRANKINE, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_FAHRENHEITREAUMUR, EXPR_NODEFUNC_FAHRENHEITREAUMUR, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE(IDENTIFIER_REAUMURRANKINE, EXPR_NODEFUNC_REAUMURRANKINE, 2, 2, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_SPEED, EXPR_NODEFUNC_SPEED, 2, 2, 0, 0);

    EXPR_ADDFUNC_TYPE(IDENTIFIER_DAY, EXPR_NODEFUNC_DAY, 3, 3, 0, 0);

    //
    EXPR_ADDFUNC_TYPE("if", EXPR_NODEFUNC_IF, 3, 3, 0, 0);
    EXPR_ADDFUNC_TYPE("select", EXPR_NODEFUNC_SELECT, 3, 4, 0, 0);
    EXPR_ADDFUNC_TYPE("equal", EXPR_NODEFUNC_EQUAL, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("above", EXPR_NODEFUNC_ABOVE, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("below", EXPR_NODEFUNC_BELOW, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("avg", EXPR_NODEFUNC_AVG, 1, -1, 0, 0);
    EXPR_ADDFUNC_TYPE("clip", EXPR_NODEFUNC_CLIP, 3, 3, 0, 0);
    EXPR_ADDFUNC_TYPE("clamp", EXPR_NODEFUNC_CLAMP, 3, 3, 0, 0);
    EXPR_ADDFUNC_TYPE("pntchange", EXPR_NODEFUNC_PNTCHANGE, 5, 5, 0, 0);
    EXPR_ADDFUNC_TYPE("poly", EXPR_NODEFUNC_POLY, 2, -1, 0, 0);
    EXPR_ADDFUNC_TYPE("and", EXPR_NODEFUNC_AND, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("or", EXPR_NODEFUNC_OR, 2, 2, 0, 0);
    EXPR_ADDFUNC_TYPE("not", EXPR_NODEFUNC_NOT, 1 ,1, 0, 0);
    EXPR_ADDFUNC_TYPE("for", EXPR_NODEFUNC_FOR, 4, -1, 0, 0);
    EXPR_ADDFUNC_TYPE("many", EXPR_NODEFUNC_MANY, 1, -1, 0, 0);

    return EXPR_ERROR_NOERROR;
    }

/* Call this function to initialize some constants into a value list */
int exprValListInit(exprValList *vlist)
    {
    int err;

    if(vlist == NULL)
        return EXPR_ERROR_NULLPOINTER;

    EXPR_ADDCONST("M_E", M_E);
    EXPR_ADDCONST("M_LOG2E", M_LOG2E);
    EXPR_ADDCONST("M_LOG10E", M_LOG10E);
    EXPR_ADDCONST("M_LN2", M_LN2);
    EXPR_ADDCONST("M_LN10", M_LN10);
    EXPR_ADDCONST("M_PI", M_PI);
    EXPR_ADDCONST("M_PI_2", M_PI_2);
    EXPR_ADDCONST("M_PI_4", M_PI_4);
    EXPR_ADDCONST("M_1_PI", M_1_PI);
    EXPR_ADDCONST("M_2_PI", M_2_PI);
    EXPR_ADDCONST("M_1_SQRTPI", M_1_SQRTPI);
    EXPR_ADDCONST("M_2_SQRTPI", M_2_SQRTPI);
    EXPR_ADDCONST("M_SQRT2", M_SQRT2);
    EXPR_ADDCONST("M_1_SQRT2", M_1_SQRT2);

    // Physics constants
    EXPR_ADDCONST("F_G", F_G);
    EXPR_ADDCONST("F_GA", F_GA);
    EXPR_ADDCONST("F_LA", F_LA);
    EXPR_ADDCONST("F_MRS", F_MRS);
    EXPR_ADDCONST("F_KB", F_KB);
    EXPR_ADDCONST("F_R", F_R);
    EXPR_ADDCONST("F_C", F_C);
    EXPR_ADDCONST("F_EPS0", F_EPS0);
    EXPR_ADDCONST("F_MI0", F_MI0);
    EXPR_ADDCONST("F_P", F_P);
    EXPR_ADDCONST("F_EC", F_EC);
    EXPR_ADDCONST("F_ESM", F_ESM);
    EXPR_ADDCONST("F_PSM", F_PSM);
    EXPR_ADDCONST("F_NSM", F_NSM);
    EXPR_ADDCONST("F_AMU", F_AMU);
    EXPR_ADDCONST("F_AV", F_AV);
    EXPR_ADDCONST("F_F", F_F);
    EXPR_ADDCONST("F_ALPHA", F_ALPHA);
    EXPR_ADDCONST("F_BHR", F_BHR);
    EXPR_ADDCONST("F_RDB", F_RDB);
    EXPR_ADDCONST("F_MBHR", F_MBHR);
    EXPR_ADDCONST("F_IV", F_IV);
    EXPR_ADDCONST("F_EH", F_EH);
    EXPR_ADDCONST("F_EMM", F_EMM);
    EXPR_ADDCONST("F_EMP", F_EMP);
    EXPR_ADDCONST("F_NM", F_NM);
    EXPR_ADDCONST("F_PGMR", F_PGMR);
    EXPR_ADDCONST("F_SB", F_SB);
    EXPR_ADDCONST("F_FR", F_FR);
    EXPR_ADDCONST("F_SR", F_SR);

    // Informatic Bit Constants
    EXPR_ADDCONST("M_KIB", M_KIB);
    EXPR_ADDCONST("M_MIB", M_MIB);
    EXPR_ADDCONST("M_GIB", M_GIB);
    EXPR_ADDCONST("M_TIB", M_TIB);
    EXPR_ADDCONST("M_PIB", M_PIB);
    EXPR_ADDCONST("M_EIB", M_EIB);

    // Time constants

    EXPR_ADDCONST("T_M", T_M);
    EXPR_ADDCONST("T_H", T_H);
    EXPR_ADDCONST("T_D", T_D);
    EXPR_ADDCONST("T_W", T_W);
    EXPR_ADDCONST("T_MT", T_MT);
    EXPR_ADDCONST("T_M1", T_M1);
    EXPR_ADDCONST("T_BM", T_BM);
    EXPR_ADDCONST("T_BM1", T_BM1);
    EXPR_ADDCONST("T_Y", T_Y);
    EXPR_ADDCONST("T_Y1", T_Y1);
    EXPR_ADDCONST("T_BY", T_BY);
    EXPR_ADDCONST("T_BY1", T_BY1);

    return EXPR_ERROR_NOERROR;
    }


